// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: steamonline/v1/steamonline.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamOnlineServiceGetOnlinePlayers = "/steamonline.v1.SteamOnlineService/GetOnlinePlayers"

type SteamOnlineServiceHTTPServer interface {
	// GetOnlinePlayers GetOnlinePlayers 返回指定游戏当前的 Steam 在线玩家数。
	// source 为空时由服务端按内置策略选择数据源。
	// 返回 NOT_FOUND 表示该 app 不存在或无法获取在线玩家数。
	GetOnlinePlayers(context.Context, *GetOnlinePlayersRequest) (*OnlinePlayers, error)
}

func RegisterSteamOnlineServiceHTTPServer(s *http.Server, srv SteamOnlineServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamonline/players/{app_id}", _SteamOnlineService_GetOnlinePlayers0_HTTP_Handler(srv))
}

func _SteamOnlineService_GetOnlinePlayers0_HTTP_Handler(srv SteamOnlineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOnlinePlayersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamOnlineServiceGetOnlinePlayers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOnlinePlayers(ctx, req.(*GetOnlinePlayersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OnlinePlayers)
		return ctx.Result(200, reply)
	}
}

type SteamOnlineServiceHTTPClient interface {
	// GetOnlinePlayers GetOnlinePlayers 返回指定游戏当前的 Steam 在线玩家数。
	// source 为空时由服务端按内置策略选择数据源。
	// 返回 NOT_FOUND 表示该 app 不存在或无法获取在线玩家数。
	GetOnlinePlayers(ctx context.Context, req *GetOnlinePlayersRequest, opts ...http.CallOption) (rsp *OnlinePlayers, err error)
}

type SteamOnlineServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamOnlineServiceHTTPClient(client *http.Client) SteamOnlineServiceHTTPClient {
	return &SteamOnlineServiceHTTPClientImpl{client}
}

// GetOnlinePlayers GetOnlinePlayers 返回指定游戏当前的 Steam 在线玩家数。
// source 为空时由服务端按内置策略选择数据源。
// 返回 NOT_FOUND 表示该 app 不存在或无法获取在线玩家数。
func (c *SteamOnlineServiceHTTPClientImpl) GetOnlinePlayers(ctx context.Context, in *GetOnlinePlayersRequest, opts ...http.CallOption) (*OnlinePlayers, error) {
	var out OnlinePlayers
	pattern := "/v1/steamonline/players/{app_id}"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamOnlineServiceGetOnlinePlayers),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
