// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamonline/v1/steamonline.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamOnlineService_GetOnlinePlayers_FullMethodName = "/steamonline.v1.SteamOnlineService/GetOnlinePlayers"
)

// SteamOnlineServiceClient is the client API for SteamOnlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamOnlineService 提供 Steam 在线玩家数查询能力。
// 对应 steam-tasks 中 handlers/steam_online 的 SteamOnlineAPI 客户端逻辑，
// 支持四种数据源抓取在线玩家数。
type SteamOnlineServiceClient interface {
	// GetOnlinePlayers 返回指定游戏当前的 Steam 在线玩家数。
	// source 为空时由服务端按内置策略选择数据源。
	// 返回 NOT_FOUND 表示该 app 不存在或无法获取在线玩家数。
	GetOnlinePlayers(ctx context.Context, in *GetOnlinePlayersRequest, opts ...grpc.CallOption) (*OnlinePlayers, error)
}

type steamOnlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamOnlineServiceClient(cc grpc.ClientConnInterface) SteamOnlineServiceClient {
	return &steamOnlineServiceClient{cc}
}

func (c *steamOnlineServiceClient) GetOnlinePlayers(ctx context.Context, in *GetOnlinePlayersRequest, opts ...grpc.CallOption) (*OnlinePlayers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlinePlayers)
	err := c.cc.Invoke(ctx, SteamOnlineService_GetOnlinePlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamOnlineServiceServer is the server API for SteamOnlineService service.
// All implementations must embed UnimplementedSteamOnlineServiceServer
// for forward compatibility.
//
// SteamOnlineService 提供 Steam 在线玩家数查询能力。
// 对应 steam-tasks 中 handlers/steam_online 的 SteamOnlineAPI 客户端逻辑，
// 支持四种数据源抓取在线玩家数。
type SteamOnlineServiceServer interface {
	// GetOnlinePlayers 返回指定游戏当前的 Steam 在线玩家数。
	// source 为空时由服务端按内置策略选择数据源。
	// 返回 NOT_FOUND 表示该 app 不存在或无法获取在线玩家数。
	GetOnlinePlayers(context.Context, *GetOnlinePlayersRequest) (*OnlinePlayers, error)
	mustEmbedUnimplementedSteamOnlineServiceServer()
}

// UnimplementedSteamOnlineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamOnlineServiceServer struct{}

func (UnimplementedSteamOnlineServiceServer) GetOnlinePlayers(context.Context, *GetOnlinePlayersRequest) (*OnlinePlayers, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlinePlayers not implemented")
}
func (UnimplementedSteamOnlineServiceServer) mustEmbedUnimplementedSteamOnlineServiceServer() {}
func (UnimplementedSteamOnlineServiceServer) testEmbeddedByValue()                            {}

// UnsafeSteamOnlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamOnlineServiceServer will
// result in compilation errors.
type UnsafeSteamOnlineServiceServer interface {
	mustEmbedUnimplementedSteamOnlineServiceServer()
}

func RegisterSteamOnlineServiceServer(s grpc.ServiceRegistrar, srv SteamOnlineServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamOnlineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamOnlineService_ServiceDesc, srv)
}

func _SteamOnlineService_GetOnlinePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlinePlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamOnlineServiceServer).GetOnlinePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamOnlineService_GetOnlinePlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamOnlineServiceServer).GetOnlinePlayers(ctx, req.(*GetOnlinePlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamOnlineService_ServiceDesc is the grpc.ServiceDesc for SteamOnlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamOnlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamonline.v1.SteamOnlineService",
	HandlerType: (*SteamOnlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnlinePlayers",
			Handler:    _SteamOnlineService_GetOnlinePlayers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamonline/v1/steamonline.proto",
}
