// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamonline/v1/steamonline.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOnlinePlayersSource int32

const (
	// 未指定数据源，由服务端按内置策略选择。
	GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED GetOnlinePlayersSource = 0
	// Steam Web API
	GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_WEB_API GetOnlinePlayersSource = 1
	// Steam 社区 HTML（走负载均衡 URL）
	GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_STEAM_COMMUNITY_HTML GetOnlinePlayersSource = 2
	// 本地代理请求社区 HTML
	GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_LOCAL_REQUEST_STEAM_COMMUNITY_HTML_WITH_PROXY GetOnlinePlayersSource = 3
	// 转发请求到远程服务器
	GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_FORWARD_REQUEST_REMOTE_SERVER GetOnlinePlayersSource = 4
)

// Enum value maps for GetOnlinePlayersSource.
var (
	GetOnlinePlayersSource_name = map[int32]string{
		0: "GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED",
		1: "GET_ONLINE_PLAYERS_SOURCE_WEB_API",
		2: "GET_ONLINE_PLAYERS_SOURCE_STEAM_COMMUNITY_HTML",
		3: "GET_ONLINE_PLAYERS_SOURCE_LOCAL_REQUEST_STEAM_COMMUNITY_HTML_WITH_PROXY",
		4: "GET_ONLINE_PLAYERS_SOURCE_FORWARD_REQUEST_REMOTE_SERVER",
	}
	GetOnlinePlayersSource_value = map[string]int32{
		"GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED":                                   0,
		"GET_ONLINE_PLAYERS_SOURCE_WEB_API":                                       1,
		"GET_ONLINE_PLAYERS_SOURCE_STEAM_COMMUNITY_HTML":                          2,
		"GET_ONLINE_PLAYERS_SOURCE_LOCAL_REQUEST_STEAM_COMMUNITY_HTML_WITH_PROXY": 3,
		"GET_ONLINE_PLAYERS_SOURCE_FORWARD_REQUEST_REMOTE_SERVER":                 4,
	}
)

func (x GetOnlinePlayersSource) Enum() *GetOnlinePlayersSource {
	p := new(GetOnlinePlayersSource)
	*p = x
	return p
}

func (x GetOnlinePlayersSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetOnlinePlayersSource) Descriptor() protoreflect.EnumDescriptor {
	return file_steamonline_v1_steamonline_proto_enumTypes[0].Descriptor()
}

func (GetOnlinePlayersSource) Type() protoreflect.EnumType {
	return &file_steamonline_v1_steamonline_proto_enumTypes[0]
}

func (x GetOnlinePlayersSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetOnlinePlayersSource.Descriptor instead.
func (GetOnlinePlayersSource) EnumDescriptor() ([]byte, []int) {
	return file_steamonline_v1_steamonline_proto_rawDescGZIP(), []int{0}
}

// GetOnlinePlayersRequest 是 SteamOnlineService.GetOnlinePlayers 的输入。
type GetOnlinePlayersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏的 Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 可选数据源，枚举值：
	//   * `web_api` - Steam Web API
	//   * `steam_community_html` - Steam 社区 HTML（走负载均衡 URL）
	//   * `local_request_steam_community_html_with_proxy` - 本地代理请求社区 HTML
	//   * `forward_request_remote_server` - 转发请求到远程服务器
	// 为空时由服务端按内置策略选择。
	Source        GetOnlinePlayersSource `protobuf:"varint,2,opt,name=source,proto3,enum=steamonline.v1.GetOnlinePlayersSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlinePlayersRequest) Reset() {
	*x = GetOnlinePlayersRequest{}
	mi := &file_steamonline_v1_steamonline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlinePlayersRequest) ProtoMessage() {}

func (x *GetOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamonline_v1_steamonline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_steamonline_v1_steamonline_proto_rawDescGZIP(), []int{0}
}

func (x *GetOnlinePlayersRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetOnlinePlayersRequest) GetSource() GetOnlinePlayersSource {
	if x != nil {
		return x.Source
	}
	return GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED
}

// OnlinePlayers 是一次在线玩家数查询结果。
type OnlinePlayers struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏的 Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 当前在线玩家数。
	PlayerCount int32 `protobuf:"varint,2,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	// 实际使用的数据源，取值见 GetOnlinePlayersRequest.source。
	Source GetOnlinePlayersSource `protobuf:"varint,3,opt,name=source,proto3,enum=steamonline.v1.GetOnlinePlayersSource" json:"source,omitempty"`
	// 抓取完成时间。
	FetchedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePlayers) Reset() {
	*x = OnlinePlayers{}
	mi := &file_steamonline_v1_steamonline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePlayers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayers) ProtoMessage() {}

func (x *OnlinePlayers) ProtoReflect() protoreflect.Message {
	mi := &file_steamonline_v1_steamonline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayers.ProtoReflect.Descriptor instead.
func (*OnlinePlayers) Descriptor() ([]byte, []int) {
	return file_steamonline_v1_steamonline_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePlayers) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *OnlinePlayers) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *OnlinePlayers) GetSource() GetOnlinePlayersSource {
	if x != nil {
		return x.Source
	}
	return GetOnlinePlayersSource_GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED
}

func (x *OnlinePlayers) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

var File_steamonline_v1_steamonline_proto protoreflect.FileDescriptor

const file_steamonline_v1_steamonline_proto_rawDesc = "" +
	"\n" +
	" steamonline/v1/steamonline.proto\x12\x0esteamonline.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x17GetOnlinePlayersRequest\x12\x1a\n" +
	"\x06app_id\x18\x01 \x01(\x05B\x03\xe0A\x02R\x05appId\x12>\n" +
	"\x06source\x18\x02 \x01(\x0e2&.steamonline.v1.GetOnlinePlayersSourceR\x06source\"\xc4\x01\n" +
	"\rOnlinePlayers\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12!\n" +
	"\fplayer_count\x18\x02 \x01(\x05R\vplayerCount\x12>\n" +
	"\x06source\x18\x03 \x01(\x0e2&.steamonline.v1.GetOnlinePlayersSourceR\x06source\x129\n" +
	"\n" +
	"fetched_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt*\xa8\x02\n" +
	"\x16GetOnlinePlayersSource\x12)\n" +
	"%GET_ONLINE_PLAYERS_SOURCE_UNSPECIFIED\x10\x00\x12%\n" +
	"!GET_ONLINE_PLAYERS_SOURCE_WEB_API\x10\x01\x122\n" +
	".GET_ONLINE_PLAYERS_SOURCE_STEAM_COMMUNITY_HTML\x10\x02\x12K\n" +
	"GGET_ONLINE_PLAYERS_SOURCE_LOCAL_REQUEST_STEAM_COMMUNITY_HTML_WITH_PROXY\x10\x03\x12;\n" +
	"7GET_ONLINE_PLAYERS_SOURCE_FORWARD_REQUEST_REMOTE_SERVER\x10\x042\x9b\x01\n" +
	"\x12SteamOnlineService\x12\x84\x01\n" +
	"\x10GetOnlinePlayers\x12'.steamonline.v1.GetOnlinePlayersRequest\x1a\x1d.steamonline.v1.OnlinePlayers\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/steamonline/players/{app_id}B`\n" +
	"\x0esteamonline.v1B\x10SteamOnlineProtoP\x01Z:github.com/shitamachi/steam-proto-go/api/steamonline/v1;v1b\x06proto3"

var (
	file_steamonline_v1_steamonline_proto_rawDescOnce sync.Once
	file_steamonline_v1_steamonline_proto_rawDescData []byte
)

func file_steamonline_v1_steamonline_proto_rawDescGZIP() []byte {
	file_steamonline_v1_steamonline_proto_rawDescOnce.Do(func() {
		file_steamonline_v1_steamonline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamonline_v1_steamonline_proto_rawDesc), len(file_steamonline_v1_steamonline_proto_rawDesc)))
	})
	return file_steamonline_v1_steamonline_proto_rawDescData
}

var file_steamonline_v1_steamonline_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steamonline_v1_steamonline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steamonline_v1_steamonline_proto_goTypes = []any{
	(GetOnlinePlayersSource)(0),     // 0: steamonline.v1.GetOnlinePlayersSource
	(*GetOnlinePlayersRequest)(nil), // 1: steamonline.v1.GetOnlinePlayersRequest
	(*OnlinePlayers)(nil),           // 2: steamonline.v1.OnlinePlayers
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_steamonline_v1_steamonline_proto_depIdxs = []int32{
	0, // 0: steamonline.v1.GetOnlinePlayersRequest.source:type_name -> steamonline.v1.GetOnlinePlayersSource
	0, // 1: steamonline.v1.OnlinePlayers.source:type_name -> steamonline.v1.GetOnlinePlayersSource
	3, // 2: steamonline.v1.OnlinePlayers.fetched_at:type_name -> google.protobuf.Timestamp
	1, // 3: steamonline.v1.SteamOnlineService.GetOnlinePlayers:input_type -> steamonline.v1.GetOnlinePlayersRequest
	2, // 4: steamonline.v1.SteamOnlineService.GetOnlinePlayers:output_type -> steamonline.v1.OnlinePlayers
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_steamonline_v1_steamonline_proto_init() }
func file_steamonline_v1_steamonline_proto_init() {
	if File_steamonline_v1_steamonline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamonline_v1_steamonline_proto_rawDesc), len(file_steamonline_v1_steamonline_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamonline_v1_steamonline_proto_goTypes,
		DependencyIndexes: file_steamonline_v1_steamonline_proto_depIdxs,
		EnumInfos:         file_steamonline_v1_steamonline_proto_enumTypes,
		MessageInfos:      file_steamonline_v1_steamonline_proto_msgTypes,
	}.Build()
	File_steamonline_v1_steamonline_proto = out.File
	file_steamonline_v1_steamonline_proto_goTypes = nil
	file_steamonline_v1_steamonline_proto_depIdxs = nil
}
