// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: steamallgames/v1/steamallgames.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamAllGamesServiceGetAppListV2 = "/steamallgames.v1.SteamAllGamesService/GetAppListV2"
const OperationSteamAllGamesServiceGetStoreAppList = "/steamallgames.v1.SteamAllGamesService/GetStoreAppList"

type SteamAllGamesServiceHTTPServer interface {
	// GetAppListV2 GetAppListV2 使用 ISteamApps/GetAppList/v2 获取全部应用列表（一次性返回）。
	GetAppListV2(context.Context, *GetAppListV2Request) (*GetAppListV2Response, error)
	// GetStoreAppList GetStoreAppList 使用 IStoreService/GetAppList/v1 获取单页应用列表，
	// 调用方用 last_appid/have_more_results 循环翻页取全量。
	// 服务端单页上限 5k（请求更大值会被钳制），避免大包超 gRPC 消息限制。
	GetStoreAppList(context.Context, *GetStoreAppListRequest) (*GetStoreAppListResponse, error)
}

func RegisterSteamAllGamesServiceHTTPServer(s *http.Server, srv SteamAllGamesServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamallgames/apps", _SteamAllGamesService_GetAppListV20_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamallgames/store-apps", _SteamAllGamesService_GetStoreAppList0_HTTP_Handler(srv))
}

func _SteamAllGamesService_GetAppListV20_HTTP_Handler(srv SteamAllGamesServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppListV2Request
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamAllGamesServiceGetAppListV2)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppListV2(ctx, req.(*GetAppListV2Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppListV2Response)
		return ctx.Result(200, reply)
	}
}

func _SteamAllGamesService_GetStoreAppList0_HTTP_Handler(srv SteamAllGamesServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStoreAppListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamAllGamesServiceGetStoreAppList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStoreAppList(ctx, req.(*GetStoreAppListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStoreAppListResponse)
		return ctx.Result(200, reply)
	}
}

type SteamAllGamesServiceHTTPClient interface {
	// GetAppListV2 GetAppListV2 使用 ISteamApps/GetAppList/v2 获取全部应用列表（一次性返回）。
	GetAppListV2(ctx context.Context, req *GetAppListV2Request, opts ...http.CallOption) (rsp *GetAppListV2Response, err error)
	// GetStoreAppList GetStoreAppList 使用 IStoreService/GetAppList/v1 获取单页应用列表，
	// 调用方用 last_appid/have_more_results 循环翻页取全量。
	// 服务端单页上限 5k（请求更大值会被钳制），避免大包超 gRPC 消息限制。
	GetStoreAppList(ctx context.Context, req *GetStoreAppListRequest, opts ...http.CallOption) (rsp *GetStoreAppListResponse, err error)
}

type SteamAllGamesServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamAllGamesServiceHTTPClient(client *http.Client) SteamAllGamesServiceHTTPClient {
	return &SteamAllGamesServiceHTTPClientImpl{client}
}

// GetAppListV2 GetAppListV2 使用 ISteamApps/GetAppList/v2 获取全部应用列表（一次性返回）。
func (c *SteamAllGamesServiceHTTPClientImpl) GetAppListV2(ctx context.Context, in *GetAppListV2Request, opts ...http.CallOption) (*GetAppListV2Response, error) {
	var out GetAppListV2Response
	pattern := "/v1/steamallgames/apps"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamAllGamesServiceGetAppListV2),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStoreAppList GetStoreAppList 使用 IStoreService/GetAppList/v1 获取单页应用列表，
// 调用方用 last_appid/have_more_results 循环翻页取全量。
// 服务端单页上限 5k（请求更大值会被钳制），避免大包超 gRPC 消息限制。
func (c *SteamAllGamesServiceHTTPClientImpl) GetStoreAppList(ctx context.Context, in *GetStoreAppListRequest, opts ...http.CallOption) (*GetStoreAppListResponse, error) {
	var out GetStoreAppListResponse
	pattern := "/v1/steamallgames/store-apps"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamAllGamesServiceGetStoreAppList),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
