// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamallgames/v1/steamallgames.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppInfo 是一个 Steam 应用的基本信息（ISteamApps/GetAppList/v2）。
type AppInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用 ID。
	Appid int32 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	// 应用名称。
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{0}
}

func (x *AppInfo) GetAppid() int32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// StoreAppInfo 是一个 Steam 商店应用信息（IStoreService/GetAppList/v1）。
type StoreAppInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用 ID。
	Appid int64 `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	// 应用名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 最后修改时间戳。
	LastModified uint32 `protobuf:"varint,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	// 价格变更号。
	PriceChangeNumber uint32 `protobuf:"varint,4,opt,name=price_change_number,json=priceChangeNumber,proto3" json:"price_change_number,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreAppInfo) Reset() {
	*x = StoreAppInfo{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAppInfo) ProtoMessage() {}

func (x *StoreAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAppInfo.ProtoReflect.Descriptor instead.
func (*StoreAppInfo) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{1}
}

func (x *StoreAppInfo) GetAppid() int64 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *StoreAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreAppInfo) GetLastModified() uint32 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *StoreAppInfo) GetPriceChangeNumber() uint32 {
	if x != nil {
		return x.PriceChangeNumber
	}
	return 0
}

// GetAppListV2Request 是 SteamAllGamesService.GetAppListV2 的输入。
type GetAppListV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppListV2Request) Reset() {
	*x = GetAppListV2Request{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppListV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppListV2Request) ProtoMessage() {}

func (x *GetAppListV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppListV2Request.ProtoReflect.Descriptor instead.
func (*GetAppListV2Request) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{2}
}

// GetAppListV2Response 是 SteamAllGamesService.GetAppListV2 的输出。
type GetAppListV2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全部应用列表。
	Apps          []*AppInfo `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppListV2Response) Reset() {
	*x = GetAppListV2Response{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppListV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppListV2Response) ProtoMessage() {}

func (x *GetAppListV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppListV2Response.ProtoReflect.Descriptor instead.
func (*GetAppListV2Response) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppListV2Response) GetApps() []*AppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

// GetStoreAppListRequest 是 SteamAllGamesService.GetStoreAppList 的输入。
type GetStoreAppListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 仅返回该时间戳之后修改的应用。
	IfModifiedSince *uint32 `protobuf:"varint,1,opt,name=if_modified_since,json=ifModifiedSince,proto3,oneof" json:"if_modified_since,omitempty"`
	// 描述语言过滤。
	HaveDescriptionLanguage string `protobuf:"bytes,2,opt,name=have_description_language,json=haveDescriptionLanguage,proto3" json:"have_description_language,omitempty"`
	// 是否包含游戏。未指定时按 false 处理（与 store API 默认值对齐）。
	IncludeGames *bool `protobuf:"varint,3,opt,name=include_games,json=includeGames,proto3,oneof" json:"include_games,omitempty"`
	// 是否包含 DLC。
	IncludeDlc *bool `protobuf:"varint,4,opt,name=include_dlc,json=includeDlc,proto3,oneof" json:"include_dlc,omitempty"`
	// 是否包含软件。
	IncludeSoftware *bool `protobuf:"varint,5,opt,name=include_software,json=includeSoftware,proto3,oneof" json:"include_software,omitempty"`
	// 是否包含视频。
	IncludeVideos *bool `protobuf:"varint,6,opt,name=include_videos,json=includeVideos,proto3,oneof" json:"include_videos,omitempty"`
	// 是否包含硬件。
	IncludeHardware *bool `protobuf:"varint,7,opt,name=include_hardware,json=includeHardware,proto3,oneof" json:"include_hardware,omitempty"`
	// 分页：从该 appid 之后开始返回。
	LastAppid *uint32 `protobuf:"varint,8,opt,name=last_appid,json=lastAppid,proto3,oneof" json:"last_appid,omitempty"`
	// 每页最大数量，默认 10k，最大 50k。
	MaxResults    *uint32 `protobuf:"varint,9,opt,name=max_results,json=maxResults,proto3,oneof" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreAppListRequest) Reset() {
	*x = GetStoreAppListRequest{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreAppListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreAppListRequest) ProtoMessage() {}

func (x *GetStoreAppListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreAppListRequest.ProtoReflect.Descriptor instead.
func (*GetStoreAppListRequest) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{4}
}

func (x *GetStoreAppListRequest) GetIfModifiedSince() uint32 {
	if x != nil && x.IfModifiedSince != nil {
		return *x.IfModifiedSince
	}
	return 0
}

func (x *GetStoreAppListRequest) GetHaveDescriptionLanguage() string {
	if x != nil {
		return x.HaveDescriptionLanguage
	}
	return ""
}

func (x *GetStoreAppListRequest) GetIncludeGames() bool {
	if x != nil && x.IncludeGames != nil {
		return *x.IncludeGames
	}
	return false
}

func (x *GetStoreAppListRequest) GetIncludeDlc() bool {
	if x != nil && x.IncludeDlc != nil {
		return *x.IncludeDlc
	}
	return false
}

func (x *GetStoreAppListRequest) GetIncludeSoftware() bool {
	if x != nil && x.IncludeSoftware != nil {
		return *x.IncludeSoftware
	}
	return false
}

func (x *GetStoreAppListRequest) GetIncludeVideos() bool {
	if x != nil && x.IncludeVideos != nil {
		return *x.IncludeVideos
	}
	return false
}

func (x *GetStoreAppListRequest) GetIncludeHardware() bool {
	if x != nil && x.IncludeHardware != nil {
		return *x.IncludeHardware
	}
	return false
}

func (x *GetStoreAppListRequest) GetLastAppid() uint32 {
	if x != nil && x.LastAppid != nil {
		return *x.LastAppid
	}
	return 0
}

func (x *GetStoreAppListRequest) GetMaxResults() uint32 {
	if x != nil && x.MaxResults != nil {
		return *x.MaxResults
	}
	return 0
}

// GetStoreAppListResponse 是 SteamAllGamesService.GetStoreAppList 的输出。
type GetStoreAppListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用列表（服务端已自动翻页累积）。
	Apps []*StoreAppInfo `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	// 最后返回的应用 ID。
	LastAppid uint32 `protobuf:"varint,2,opt,name=last_appid,json=lastAppid,proto3" json:"last_appid,omitempty"`
	// 是否还有更多结果。
	HaveMoreResults bool `protobuf:"varint,3,opt,name=have_more_results,json=haveMoreResults,proto3" json:"have_more_results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStoreAppListResponse) Reset() {
	*x = GetStoreAppListResponse{}
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreAppListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreAppListResponse) ProtoMessage() {}

func (x *GetStoreAppListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_steamallgames_v1_steamallgames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreAppListResponse.ProtoReflect.Descriptor instead.
func (*GetStoreAppListResponse) Descriptor() ([]byte, []int) {
	return file_steamallgames_v1_steamallgames_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoreAppListResponse) GetApps() []*StoreAppInfo {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *GetStoreAppListResponse) GetLastAppid() uint32 {
	if x != nil {
		return x.LastAppid
	}
	return 0
}

func (x *GetStoreAppListResponse) GetHaveMoreResults() bool {
	if x != nil {
		return x.HaveMoreResults
	}
	return false
}

var File_steamallgames_v1_steamallgames_proto protoreflect.FileDescriptor

const file_steamallgames_v1_steamallgames_proto_rawDesc = "" +
	"\n" +
	"$steamallgames/v1/steamallgames.proto\x12\x10steamallgames.v1\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\aAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\x05R\x05appid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8d\x01\n" +
	"\fStoreAppInfo\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\x03R\x05appid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rlast_modified\x18\x03 \x01(\rR\flastModified\x12.\n" +
	"\x13price_change_number\x18\x04 \x01(\rR\x11priceChangeNumber\"\x15\n" +
	"\x13GetAppListV2Request\"E\n" +
	"\x14GetAppListV2Response\x12-\n" +
	"\x04apps\x18\x01 \x03(\v2\x19.steamallgames.v1.AppInfoR\x04apps\"\xbf\x04\n" +
	"\x16GetStoreAppListRequest\x12/\n" +
	"\x11if_modified_since\x18\x01 \x01(\rH\x00R\x0fifModifiedSince\x88\x01\x01\x12:\n" +
	"\x19have_description_language\x18\x02 \x01(\tR\x17haveDescriptionLanguage\x12(\n" +
	"\rinclude_games\x18\x03 \x01(\bH\x01R\fincludeGames\x88\x01\x01\x12$\n" +
	"\vinclude_dlc\x18\x04 \x01(\bH\x02R\n" +
	"includeDlc\x88\x01\x01\x12.\n" +
	"\x10include_software\x18\x05 \x01(\bH\x03R\x0fincludeSoftware\x88\x01\x01\x12*\n" +
	"\x0einclude_videos\x18\x06 \x01(\bH\x04R\rincludeVideos\x88\x01\x01\x12.\n" +
	"\x10include_hardware\x18\a \x01(\bH\x05R\x0fincludeHardware\x88\x01\x01\x12\"\n" +
	"\n" +
	"last_appid\x18\b \x01(\rH\x06R\tlastAppid\x88\x01\x01\x12$\n" +
	"\vmax_results\x18\t \x01(\rH\aR\n" +
	"maxResults\x88\x01\x01B\x14\n" +
	"\x12_if_modified_sinceB\x10\n" +
	"\x0e_include_gamesB\x0e\n" +
	"\f_include_dlcB\x13\n" +
	"\x11_include_softwareB\x11\n" +
	"\x0f_include_videosB\x13\n" +
	"\x11_include_hardwareB\r\n" +
	"\v_last_appidB\x0e\n" +
	"\f_max_results\"\x98\x01\n" +
	"\x17GetStoreAppListResponse\x122\n" +
	"\x04apps\x18\x01 \x03(\v2\x1e.steamallgames.v1.StoreAppInfoR\x04apps\x12\x1d\n" +
	"\n" +
	"last_appid\x18\x02 \x01(\rR\tlastAppid\x12*\n" +
	"\x11have_more_results\x18\x03 \x01(\bR\x0fhaveMoreResults2\xa4\x02\n" +
	"\x14SteamAllGamesService\x12}\n" +
	"\fGetAppListV2\x12%.steamallgames.v1.GetAppListV2Request\x1a&.steamallgames.v1.GetAppListV2Response\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/steamallgames/apps\x12\x8c\x01\n" +
	"\x0fGetStoreAppList\x12(.steamallgames.v1.GetStoreAppListRequest\x1a).steamallgames.v1.GetStoreAppListResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/steamallgames/store-appsBf\n" +
	"\x10steamallgames.v1B\x12SteamAllGamesProtoP\x01Z<github.com/shitamachi/steam-proto-go/api/steamallgames/v1;v1b\x06proto3"

var (
	file_steamallgames_v1_steamallgames_proto_rawDescOnce sync.Once
	file_steamallgames_v1_steamallgames_proto_rawDescData []byte
)

func file_steamallgames_v1_steamallgames_proto_rawDescGZIP() []byte {
	file_steamallgames_v1_steamallgames_proto_rawDescOnce.Do(func() {
		file_steamallgames_v1_steamallgames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamallgames_v1_steamallgames_proto_rawDesc), len(file_steamallgames_v1_steamallgames_proto_rawDesc)))
	})
	return file_steamallgames_v1_steamallgames_proto_rawDescData
}

var file_steamallgames_v1_steamallgames_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_steamallgames_v1_steamallgames_proto_goTypes = []any{
	(*AppInfo)(nil),                 // 0: steamallgames.v1.AppInfo
	(*StoreAppInfo)(nil),            // 1: steamallgames.v1.StoreAppInfo
	(*GetAppListV2Request)(nil),     // 2: steamallgames.v1.GetAppListV2Request
	(*GetAppListV2Response)(nil),    // 3: steamallgames.v1.GetAppListV2Response
	(*GetStoreAppListRequest)(nil),  // 4: steamallgames.v1.GetStoreAppListRequest
	(*GetStoreAppListResponse)(nil), // 5: steamallgames.v1.GetStoreAppListResponse
}
var file_steamallgames_v1_steamallgames_proto_depIdxs = []int32{
	0, // 0: steamallgames.v1.GetAppListV2Response.apps:type_name -> steamallgames.v1.AppInfo
	1, // 1: steamallgames.v1.GetStoreAppListResponse.apps:type_name -> steamallgames.v1.StoreAppInfo
	2, // 2: steamallgames.v1.SteamAllGamesService.GetAppListV2:input_type -> steamallgames.v1.GetAppListV2Request
	4, // 3: steamallgames.v1.SteamAllGamesService.GetStoreAppList:input_type -> steamallgames.v1.GetStoreAppListRequest
	3, // 4: steamallgames.v1.SteamAllGamesService.GetAppListV2:output_type -> steamallgames.v1.GetAppListV2Response
	5, // 5: steamallgames.v1.SteamAllGamesService.GetStoreAppList:output_type -> steamallgames.v1.GetStoreAppListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_steamallgames_v1_steamallgames_proto_init() }
func file_steamallgames_v1_steamallgames_proto_init() {
	if File_steamallgames_v1_steamallgames_proto != nil {
		return
	}
	file_steamallgames_v1_steamallgames_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamallgames_v1_steamallgames_proto_rawDesc), len(file_steamallgames_v1_steamallgames_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamallgames_v1_steamallgames_proto_goTypes,
		DependencyIndexes: file_steamallgames_v1_steamallgames_proto_depIdxs,
		MessageInfos:      file_steamallgames_v1_steamallgames_proto_msgTypes,
	}.Build()
	File_steamallgames_v1_steamallgames_proto = out.File
	file_steamallgames_v1_steamallgames_proto_goTypes = nil
	file_steamallgames_v1_steamallgames_proto_depIdxs = nil
}
