// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamallgames/v1/steamallgames.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamAllGamesService_GetAppListV2_FullMethodName    = "/steamallgames.v1.SteamAllGamesService/GetAppListV2"
	SteamAllGamesService_GetStoreAppList_FullMethodName = "/steamallgames.v1.SteamAllGamesService/GetStoreAppList"
)

// SteamAllGamesServiceClient is the client API for SteamAllGamesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamAllGamesService 提供 Steam 应用列表抓取能力。
// 对应 steam-tasks 中 handlers/steam_all_games 的 SteamAppListAPI 客户端逻辑。
type SteamAllGamesServiceClient interface {
	// GetAppListV2 使用 ISteamApps/GetAppList/v2 获取全部应用列表（一次性返回）。
	GetAppListV2(ctx context.Context, in *GetAppListV2Request, opts ...grpc.CallOption) (*GetAppListV2Response, error)
	// GetStoreAppList 使用 IStoreService/GetAppList/v1 获取单页应用列表，
	// 调用方用 last_appid/have_more_results 循环翻页取全量。
	// 服务端单页上限 5k（请求更大值会被钳制），避免大包超 gRPC 消息限制。
	GetStoreAppList(ctx context.Context, in *GetStoreAppListRequest, opts ...grpc.CallOption) (*GetStoreAppListResponse, error)
}

type steamAllGamesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamAllGamesServiceClient(cc grpc.ClientConnInterface) SteamAllGamesServiceClient {
	return &steamAllGamesServiceClient{cc}
}

func (c *steamAllGamesServiceClient) GetAppListV2(ctx context.Context, in *GetAppListV2Request, opts ...grpc.CallOption) (*GetAppListV2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppListV2Response)
	err := c.cc.Invoke(ctx, SteamAllGamesService_GetAppListV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steamAllGamesServiceClient) GetStoreAppList(ctx context.Context, in *GetStoreAppListRequest, opts ...grpc.CallOption) (*GetStoreAppListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreAppListResponse)
	err := c.cc.Invoke(ctx, SteamAllGamesService_GetStoreAppList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamAllGamesServiceServer is the server API for SteamAllGamesService service.
// All implementations must embed UnimplementedSteamAllGamesServiceServer
// for forward compatibility.
//
// SteamAllGamesService 提供 Steam 应用列表抓取能力。
// 对应 steam-tasks 中 handlers/steam_all_games 的 SteamAppListAPI 客户端逻辑。
type SteamAllGamesServiceServer interface {
	// GetAppListV2 使用 ISteamApps/GetAppList/v2 获取全部应用列表（一次性返回）。
	GetAppListV2(context.Context, *GetAppListV2Request) (*GetAppListV2Response, error)
	// GetStoreAppList 使用 IStoreService/GetAppList/v1 获取单页应用列表，
	// 调用方用 last_appid/have_more_results 循环翻页取全量。
	// 服务端单页上限 5k（请求更大值会被钳制），避免大包超 gRPC 消息限制。
	GetStoreAppList(context.Context, *GetStoreAppListRequest) (*GetStoreAppListResponse, error)
	mustEmbedUnimplementedSteamAllGamesServiceServer()
}

// UnimplementedSteamAllGamesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamAllGamesServiceServer struct{}

func (UnimplementedSteamAllGamesServiceServer) GetAppListV2(context.Context, *GetAppListV2Request) (*GetAppListV2Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppListV2 not implemented")
}
func (UnimplementedSteamAllGamesServiceServer) GetStoreAppList(context.Context, *GetStoreAppListRequest) (*GetStoreAppListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreAppList not implemented")
}
func (UnimplementedSteamAllGamesServiceServer) mustEmbedUnimplementedSteamAllGamesServiceServer() {}
func (UnimplementedSteamAllGamesServiceServer) testEmbeddedByValue()                              {}

// UnsafeSteamAllGamesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamAllGamesServiceServer will
// result in compilation errors.
type UnsafeSteamAllGamesServiceServer interface {
	mustEmbedUnimplementedSteamAllGamesServiceServer()
}

func RegisterSteamAllGamesServiceServer(s grpc.ServiceRegistrar, srv SteamAllGamesServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamAllGamesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamAllGamesService_ServiceDesc, srv)
}

func _SteamAllGamesService_GetAppListV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppListV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamAllGamesServiceServer).GetAppListV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamAllGamesService_GetAppListV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamAllGamesServiceServer).GetAppListV2(ctx, req.(*GetAppListV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SteamAllGamesService_GetStoreAppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreAppListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamAllGamesServiceServer).GetStoreAppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamAllGamesService_GetStoreAppList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamAllGamesServiceServer).GetStoreAppList(ctx, req.(*GetStoreAppListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamAllGamesService_ServiceDesc is the grpc.ServiceDesc for SteamAllGamesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamAllGamesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamallgames.v1.SteamAllGamesService",
	HandlerType: (*SteamAllGamesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppListV2",
			Handler:    _SteamAllGamesService_GetAppListV2_Handler,
		},
		{
			MethodName: "GetStoreAppList",
			Handler:    _SteamAllGamesService_GetStoreAppList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamallgames/v1/steamallgames.proto",
}
