// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamdetail/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_STEAMDETAIL_UNSPECIFIED       ErrorReason = 0
	ErrorReason_STEAMDETAIL_INVALID_ARGUMENT  ErrorReason = 1
	ErrorReason_STEAMDETAIL_NETWORK           ErrorReason = 2
	ErrorReason_STEAMDETAIL_TOO_MANY_REQUESTS ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "STEAMDETAIL_UNSPECIFIED",
		1: "STEAMDETAIL_INVALID_ARGUMENT",
		2: "STEAMDETAIL_NETWORK",
		3: "STEAMDETAIL_TOO_MANY_REQUESTS",
	}
	ErrorReason_value = map[string]int32{
		"STEAMDETAIL_UNSPECIFIED":       0,
		"STEAMDETAIL_INVALID_ARGUMENT":  1,
		"STEAMDETAIL_NETWORK":           2,
		"STEAMDETAIL_TOO_MANY_REQUESTS": 3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_steamdetail_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_steamdetail_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_steamdetail_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_steamdetail_v1_error_reason_proto protoreflect.FileDescriptor

const file_steamdetail_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"!steamdetail/v1/error_reason.proto\x12\x0esteamdetail.v1*\x88\x01\n" +
	"\vErrorReason\x12\x1b\n" +
	"\x17STEAMDETAIL_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSTEAMDETAIL_INVALID_ARGUMENT\x10\x01\x12\x17\n" +
	"\x13STEAMDETAIL_NETWORK\x10\x02\x12!\n" +
	"\x1dSTEAMDETAIL_TOO_MANY_REQUESTS\x10\x03Ba\n" +
	"\x0esteamdetail.v1P\x01Z:github.com/shitamachi/steam-proto-go/api/steamdetail/v1;v1\xa2\x02\x10APISteamDetailV1b\x06proto3"

var (
	file_steamdetail_v1_error_reason_proto_rawDescOnce sync.Once
	file_steamdetail_v1_error_reason_proto_rawDescData []byte
)

func file_steamdetail_v1_error_reason_proto_rawDescGZIP() []byte {
	file_steamdetail_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_steamdetail_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamdetail_v1_error_reason_proto_rawDesc), len(file_steamdetail_v1_error_reason_proto_rawDesc)))
	})
	return file_steamdetail_v1_error_reason_proto_rawDescData
}

var file_steamdetail_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steamdetail_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: steamdetail.v1.ErrorReason
}
var file_steamdetail_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steamdetail_v1_error_reason_proto_init() }
func file_steamdetail_v1_error_reason_proto_init() {
	if File_steamdetail_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamdetail_v1_error_reason_proto_rawDesc), len(file_steamdetail_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steamdetail_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_steamdetail_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_steamdetail_v1_error_reason_proto_enumTypes,
	}.Build()
	File_steamdetail_v1_error_reason_proto = out.File
	file_steamdetail_v1_error_reason_proto_goTypes = nil
	file_steamdetail_v1_error_reason_proto_depIdxs = nil
}
