// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: steamdetail/v1/steamdetail.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamDetailServiceGetAppDetails = "/steamdetail.v1.SteamDetailService/GetAppDetails"

type SteamDetailServiceHTTPServer interface {
	// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(context.Context, *GetAppDetailsRequest) (*AppDetails, error)
}

func RegisterSteamDetailServiceHTTPServer(s *http.Server, srv SteamDetailServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamdetail/appdetails", _SteamDetailService_GetAppDetails0_HTTP_Handler(srv))
}

func _SteamDetailService_GetAppDetails0_HTTP_Handler(srv SteamDetailServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppDetailsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDetailServiceGetAppDetails)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppDetails(ctx, req.(*GetAppDetailsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppDetails)
		return ctx.Result(200, reply)
	}
}

type SteamDetailServiceHTTPClient interface {
	// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(ctx context.Context, req *GetAppDetailsRequest, opts ...http.CallOption) (rsp *AppDetails, err error)
}

type SteamDetailServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamDetailServiceHTTPClient(client *http.Client) SteamDetailServiceHTTPClient {
	return &SteamDetailServiceHTTPClientImpl{client}
}

// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
func (c *SteamDetailServiceHTTPClientImpl) GetAppDetails(ctx context.Context, in *GetAppDetailsRequest, opts ...http.CallOption) (*AppDetails, error) {
	var out AppDetails
	pattern := "/v1/steamdetail/appdetails"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDetailServiceGetAppDetails),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
