// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamdetail/v1/steamdetail.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamDetailService_GetAppDetails_FullMethodName = "/steamdetail.v1.SteamDetailService/GetAppDetails"
)

// SteamDetailServiceClient is the client API for SteamDetailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamDetailService 提供 Steam 应用详情抓取能力。
// 对应 steam-tasks 中 handlers/steam_detail 的 SteamAppDetailAPI 客户端逻辑。
type SteamDetailServiceClient interface {
	// GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(ctx context.Context, in *GetAppDetailsRequest, opts ...grpc.CallOption) (*AppDetails, error)
}

type steamDetailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamDetailServiceClient(cc grpc.ClientConnInterface) SteamDetailServiceClient {
	return &steamDetailServiceClient{cc}
}

func (c *steamDetailServiceClient) GetAppDetails(ctx context.Context, in *GetAppDetailsRequest, opts ...grpc.CallOption) (*AppDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDetails)
	err := c.cc.Invoke(ctx, SteamDetailService_GetAppDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamDetailServiceServer is the server API for SteamDetailService service.
// All implementations must embed UnimplementedSteamDetailServiceServer
// for forward compatibility.
//
// SteamDetailService 提供 Steam 应用详情抓取能力。
// 对应 steam-tasks 中 handlers/steam_detail 的 SteamAppDetailAPI 客户端逻辑。
type SteamDetailServiceServer interface {
	// GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(context.Context, *GetAppDetailsRequest) (*AppDetails, error)
	mustEmbedUnimplementedSteamDetailServiceServer()
}

// UnimplementedSteamDetailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamDetailServiceServer struct{}

func (UnimplementedSteamDetailServiceServer) GetAppDetails(context.Context, *GetAppDetailsRequest) (*AppDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppDetails not implemented")
}
func (UnimplementedSteamDetailServiceServer) mustEmbedUnimplementedSteamDetailServiceServer() {}
func (UnimplementedSteamDetailServiceServer) testEmbeddedByValue()                            {}

// UnsafeSteamDetailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamDetailServiceServer will
// result in compilation errors.
type UnsafeSteamDetailServiceServer interface {
	mustEmbedUnimplementedSteamDetailServiceServer()
}

func RegisterSteamDetailServiceServer(s grpc.ServiceRegistrar, srv SteamDetailServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamDetailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamDetailService_ServiceDesc, srv)
}

func _SteamDetailService_GetAppDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamDetailServiceServer).GetAppDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamDetailService_GetAppDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamDetailServiceServer).GetAppDetails(ctx, req.(*GetAppDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamDetailService_ServiceDesc is the grpc.ServiceDesc for SteamDetailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamDetailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamdetail.v1.SteamDetailService",
	HandlerType: (*SteamDetailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppDetails",
			Handler:    _SteamDetailService_GetAppDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamdetail/v1/steamdetail.proto",
}
