// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamdetail/v1/steamdetail.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAppDetailsRequest 是 SteamDetailService.GetAppDetails 的输入。
type GetAppDetailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要查询的应用 ID 列表。
	AppIds []int32 `protobuf:"varint,1,rep,packed,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	// Steam 语言代码，如 schinese / english。
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Steam 货币代码，如 cn / us。
	Currency string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	// 过滤字段列表（filters），为空时不限制。
	Filters []string `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	// 是否不使用 price_overview 过滤（为 true 时 filters 参数生效）。
	NoPriceOverview bool `protobuf:"varint,5,opt,name=no_price_overview,json=noPriceOverview,proto3" json:"no_price_overview,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAppDetailsRequest) Reset() {
	*x = GetAppDetailsRequest{}
	mi := &file_steamdetail_v1_steamdetail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppDetailsRequest) ProtoMessage() {}

func (x *GetAppDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamdetail_v1_steamdetail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAppDetailsRequest) Descriptor() ([]byte, []int) {
	return file_steamdetail_v1_steamdetail_proto_rawDescGZIP(), []int{0}
}

func (x *GetAppDetailsRequest) GetAppIds() []int32 {
	if x != nil {
		return x.AppIds
	}
	return nil
}

func (x *GetAppDetailsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetAppDetailsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetAppDetailsRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetAppDetailsRequest) GetNoPriceOverview() bool {
	if x != nil {
		return x.NoPriceOverview
	}
	return false
}

// AppDetails 是一次应用详情查询结果。
type AppDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 查询的应用 ID 列表。
	AppIds []int32 `protobuf:"varint,1,rep,packed,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	// api/appdetails 接口返回的原始 JSON 响应体。
	RawJson       []byte `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppDetails) Reset() {
	*x = AppDetails{}
	mi := &file_steamdetail_v1_steamdetail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppDetails) ProtoMessage() {}

func (x *AppDetails) ProtoReflect() protoreflect.Message {
	mi := &file_steamdetail_v1_steamdetail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppDetails.ProtoReflect.Descriptor instead.
func (*AppDetails) Descriptor() ([]byte, []int) {
	return file_steamdetail_v1_steamdetail_proto_rawDescGZIP(), []int{1}
}

func (x *AppDetails) GetAppIds() []int32 {
	if x != nil {
		return x.AppIds
	}
	return nil
}

func (x *AppDetails) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

var File_steamdetail_v1_steamdetail_proto protoreflect.FileDescriptor

const file_steamdetail_v1_steamdetail_proto_rawDesc = "" +
	"\n" +
	" steamdetail/v1/steamdetail.proto\x12\x0esteamdetail.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xb2\x01\n" +
	"\x14GetAppDetailsRequest\x12\x1c\n" +
	"\aapp_ids\x18\x01 \x03(\x05B\x03\xe0A\x02R\x06appIds\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\x12*\n" +
	"\x11no_price_overview\x18\x05 \x01(\bR\x0fnoPriceOverview\"@\n" +
	"\n" +
	"AppDetails\x12\x17\n" +
	"\aapp_ids\x18\x01 \x03(\x05R\x06appIds\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\fR\arawJson2\x8b\x01\n" +
	"\x12SteamDetailService\x12u\n" +
	"\rGetAppDetails\x12$.steamdetail.v1.GetAppDetailsRequest\x1a\x1a.steamdetail.v1.AppDetails\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/steamdetail/appdetailsB`\n" +
	"\x0esteamdetail.v1B\x10SteamDetailProtoP\x01Z:github.com/shitamachi/steam-proto-go/api/steamdetail/v1;v1b\x06proto3"

var (
	file_steamdetail_v1_steamdetail_proto_rawDescOnce sync.Once
	file_steamdetail_v1_steamdetail_proto_rawDescData []byte
)

func file_steamdetail_v1_steamdetail_proto_rawDescGZIP() []byte {
	file_steamdetail_v1_steamdetail_proto_rawDescOnce.Do(func() {
		file_steamdetail_v1_steamdetail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamdetail_v1_steamdetail_proto_rawDesc), len(file_steamdetail_v1_steamdetail_proto_rawDesc)))
	})
	return file_steamdetail_v1_steamdetail_proto_rawDescData
}

var file_steamdetail_v1_steamdetail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steamdetail_v1_steamdetail_proto_goTypes = []any{
	(*GetAppDetailsRequest)(nil), // 0: steamdetail.v1.GetAppDetailsRequest
	(*AppDetails)(nil),           // 1: steamdetail.v1.AppDetails
}
var file_steamdetail_v1_steamdetail_proto_depIdxs = []int32{
	0, // 0: steamdetail.v1.SteamDetailService.GetAppDetails:input_type -> steamdetail.v1.GetAppDetailsRequest
	1, // 1: steamdetail.v1.SteamDetailService.GetAppDetails:output_type -> steamdetail.v1.AppDetails
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steamdetail_v1_steamdetail_proto_init() }
func file_steamdetail_v1_steamdetail_proto_init() {
	if File_steamdetail_v1_steamdetail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamdetail_v1_steamdetail_proto_rawDesc), len(file_steamdetail_v1_steamdetail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamdetail_v1_steamdetail_proto_goTypes,
		DependencyIndexes: file_steamdetail_v1_steamdetail_proto_depIdxs,
		MessageInfos:      file_steamdetail_v1_steamdetail_proto_msgTypes,
	}.Build()
	File_steamdetail_v1_steamdetail_proto = out.File
	file_steamdetail_v1_steamdetail_proto_goTypes = nil
	file_steamdetail_v1_steamdetail_proto_depIdxs = nil
}
