// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: steamdetail/v1/steamdetail.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamDetailServiceGetAppDetails = "/steamdetail.v1.SteamDetailService/GetAppDetails"
const OperationSteamDetailServiceGetStorePageHTML = "/steamdetail.v1.SteamDetailService/GetStorePageHTML"

type SteamDetailServiceHTTPServer interface {
	// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(context.Context, *GetAppDetailsRequest) (*AppDetails, error)
	// GetStorePageHTML Fixed-purpose Store HTML collection; authentication stays inside steam-api.
	GetStorePageHTML(context.Context, *GetStorePageHTMLRequest) (*StorePageHTML, error)
}

func RegisterSteamDetailServiceHTTPServer(s *http.Server, srv SteamDetailServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamdetail/store-html", _SteamDetailService_GetStorePageHTML0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdetail/appdetails", _SteamDetailService_GetAppDetails0_HTTP_Handler(srv))
}

func _SteamDetailService_GetStorePageHTML0_HTTP_Handler(srv SteamDetailServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStorePageHTMLRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDetailServiceGetStorePageHTML)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStorePageHTML(ctx, req.(*GetStorePageHTMLRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StorePageHTML)
		return ctx.Result(200, reply)
	}
}

func _SteamDetailService_GetAppDetails0_HTTP_Handler(srv SteamDetailServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppDetailsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDetailServiceGetAppDetails)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppDetails(ctx, req.(*GetAppDetailsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppDetails)
		return ctx.Result(200, reply)
	}
}

type SteamDetailServiceHTTPClient interface {
	// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
	// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
	// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
	GetAppDetails(ctx context.Context, req *GetAppDetailsRequest, opts ...http.CallOption) (rsp *AppDetails, err error)
	// GetStorePageHTML Fixed-purpose Store HTML collection; authentication stays inside steam-api.
	GetStorePageHTML(ctx context.Context, req *GetStorePageHTMLRequest, opts ...http.CallOption) (rsp *StorePageHTML, err error)
}

type SteamDetailServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamDetailServiceHTTPClient(client *http.Client) SteamDetailServiceHTTPClient {
	return &SteamDetailServiceHTTPClientImpl{client}
}

// GetAppDetails GetAppDetails 获取指定应用（appids）的详情数据。
// 返回的 raw_json 为 api/appdetails 接口的原始 JSON 响应体
// （以 appid 为 key 的应用详情 map），解析与落库由调用方完成。
func (c *SteamDetailServiceHTTPClientImpl) GetAppDetails(ctx context.Context, in *GetAppDetailsRequest, opts ...http.CallOption) (*AppDetails, error) {
	var out AppDetails
	pattern := "/v1/steamdetail/appdetails"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDetailServiceGetAppDetails),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStorePageHTML Fixed-purpose Store HTML collection; authentication stays inside steam-api.
func (c *SteamDetailServiceHTTPClientImpl) GetStorePageHTML(ctx context.Context, in *GetStorePageHTMLRequest, opts ...http.CallOption) (*StorePageHTML, error) {
	var out StorePageHTML
	pattern := "/v1/steamdetail/store-html"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDetailServiceGetStorePageHTML),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationSteamMetadataServiceGetDeckReport = "/steamdetail.v1.SteamMetadataService/GetDeckReport"
const OperationSteamMetadataServiceGetPurchaseOptions = "/steamdetail.v1.SteamMetadataService/GetPurchaseOptions"
const OperationSteamMetadataServiceGetStoreItems = "/steamdetail.v1.SteamMetadataService/GetStoreItems"
const OperationSteamMetadataServiceGetTagList = "/steamdetail.v1.SteamMetadataService/GetTagList"

type SteamMetadataServiceHTTPServer interface {
	GetDeckReport(context.Context, *GetDeckReportRequest) (*GetDeckReportResponse, error)
	// GetPurchaseOptions Bounded purchase-option facts. Reviews are never requested.
	GetPurchaseOptions(context.Context, *GetPurchaseOptionsRequest) (*GetPurchaseOptionsResponse, error)
	GetStoreItems(context.Context, *GetStoreItemsRequest) (*GetStoreItemsResponse, error)
	GetTagList(context.Context, *GetTagListRequest) (*GetTagListResponse, error)
}

func RegisterSteamMetadataServiceHTTPServer(s *http.Server, srv SteamMetadataServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamdetail/store-items", _SteamMetadataService_GetStoreItems0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdetail/purchase-options", _SteamMetadataService_GetPurchaseOptions0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdetail/tags", _SteamMetadataService_GetTagList0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdetail/deck-report", _SteamMetadataService_GetDeckReport0_HTTP_Handler(srv))
}

func _SteamMetadataService_GetStoreItems0_HTTP_Handler(srv SteamMetadataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStoreItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamMetadataServiceGetStoreItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStoreItems(ctx, req.(*GetStoreItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStoreItemsResponse)
		return ctx.Result(200, reply)
	}
}

func _SteamMetadataService_GetPurchaseOptions0_HTTP_Handler(srv SteamMetadataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPurchaseOptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamMetadataServiceGetPurchaseOptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPurchaseOptions(ctx, req.(*GetPurchaseOptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPurchaseOptionsResponse)
		return ctx.Result(200, reply)
	}
}

func _SteamMetadataService_GetTagList0_HTTP_Handler(srv SteamMetadataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTagListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamMetadataServiceGetTagList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTagList(ctx, req.(*GetTagListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTagListResponse)
		return ctx.Result(200, reply)
	}
}

func _SteamMetadataService_GetDeckReport0_HTTP_Handler(srv SteamMetadataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeckReportRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamMetadataServiceGetDeckReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeckReport(ctx, req.(*GetDeckReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeckReportResponse)
		return ctx.Result(200, reply)
	}
}

type SteamMetadataServiceHTTPClient interface {
	GetDeckReport(ctx context.Context, req *GetDeckReportRequest, opts ...http.CallOption) (rsp *GetDeckReportResponse, err error)
	// GetPurchaseOptions Bounded purchase-option facts. Reviews are never requested.
	GetPurchaseOptions(ctx context.Context, req *GetPurchaseOptionsRequest, opts ...http.CallOption) (rsp *GetPurchaseOptionsResponse, err error)
	GetStoreItems(ctx context.Context, req *GetStoreItemsRequest, opts ...http.CallOption) (rsp *GetStoreItemsResponse, err error)
	GetTagList(ctx context.Context, req *GetTagListRequest, opts ...http.CallOption) (rsp *GetTagListResponse, err error)
}

type SteamMetadataServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamMetadataServiceHTTPClient(client *http.Client) SteamMetadataServiceHTTPClient {
	return &SteamMetadataServiceHTTPClientImpl{client}
}

func (c *SteamMetadataServiceHTTPClientImpl) GetDeckReport(ctx context.Context, in *GetDeckReportRequest, opts ...http.CallOption) (*GetDeckReportResponse, error) {
	var out GetDeckReportResponse
	pattern := "/v1/steamdetail/deck-report"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamMetadataServiceGetDeckReport),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPurchaseOptions Bounded purchase-option facts. Reviews are never requested.
func (c *SteamMetadataServiceHTTPClientImpl) GetPurchaseOptions(ctx context.Context, in *GetPurchaseOptionsRequest, opts ...http.CallOption) (*GetPurchaseOptionsResponse, error) {
	var out GetPurchaseOptionsResponse
	pattern := "/v1/steamdetail/purchase-options"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamMetadataServiceGetPurchaseOptions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SteamMetadataServiceHTTPClientImpl) GetStoreItems(ctx context.Context, in *GetStoreItemsRequest, opts ...http.CallOption) (*GetStoreItemsResponse, error) {
	var out GetStoreItemsResponse
	pattern := "/v1/steamdetail/store-items"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamMetadataServiceGetStoreItems),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SteamMetadataServiceHTTPClientImpl) GetTagList(ctx context.Context, in *GetTagListRequest, opts ...http.CallOption) (*GetTagListResponse, error) {
	var out GetTagListResponse
	pattern := "/v1/steamdetail/tags"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamMetadataServiceGetTagList),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
