// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: steamspecials/v1/steamspecials.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamSpecialsServiceFetchSpecialsPage = "/steamspecials.v1.SteamSpecialsService/FetchSpecialsPage"

type SteamSpecialsServiceHTTPServer interface {
	// FetchSpecialsPage FetchSpecialsPage 获取单页折扣游戏列表。
	// 返回的 results_html 为搜索接口返回的原始 HTML 片段，
	// 由调用方负责解析为游戏条目。
	FetchSpecialsPage(context.Context, *FetchSpecialsPageRequest) (*SpecialsPage, error)
}

func RegisterSteamSpecialsServiceHTTPServer(s *http.Server, srv SteamSpecialsServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamspecials/pages", _SteamSpecialsService_FetchSpecialsPage0_HTTP_Handler(srv))
}

func _SteamSpecialsService_FetchSpecialsPage0_HTTP_Handler(srv SteamSpecialsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FetchSpecialsPageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamSpecialsServiceFetchSpecialsPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FetchSpecialsPage(ctx, req.(*FetchSpecialsPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SpecialsPage)
		return ctx.Result(200, reply)
	}
}

type SteamSpecialsServiceHTTPClient interface {
	// FetchSpecialsPage FetchSpecialsPage 获取单页折扣游戏列表。
	// 返回的 results_html 为搜索接口返回的原始 HTML 片段，
	// 由调用方负责解析为游戏条目。
	FetchSpecialsPage(ctx context.Context, req *FetchSpecialsPageRequest, opts ...http.CallOption) (rsp *SpecialsPage, err error)
}

type SteamSpecialsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamSpecialsServiceHTTPClient(client *http.Client) SteamSpecialsServiceHTTPClient {
	return &SteamSpecialsServiceHTTPClientImpl{client}
}

// FetchSpecialsPage FetchSpecialsPage 获取单页折扣游戏列表。
// 返回的 results_html 为搜索接口返回的原始 HTML 片段，
// 由调用方负责解析为游戏条目。
func (c *SteamSpecialsServiceHTTPClientImpl) FetchSpecialsPage(ctx context.Context, in *FetchSpecialsPageRequest, opts ...http.CallOption) (*SpecialsPage, error) {
	var out SpecialsPage
	pattern := "/v1/steamspecials/pages"
	path := steamhttpbinding.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamSpecialsServiceFetchSpecialsPage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
