// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamspecials/v1/steamspecials.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamSpecialsService_FetchSpecialsPage_FullMethodName = "/steamspecials.v1.SteamSpecialsService/FetchSpecialsPage"
)

// SteamSpecialsServiceClient is the client API for SteamSpecialsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamSpecialsService 提供 Steam 折扣游戏列表抓取能力。
// 对应 steam-tasks 中 handlers/steam_specials 的 SteamSpecialsAPI 客户端逻辑。
type SteamSpecialsServiceClient interface {
	// FetchSpecialsPage 获取单页折扣游戏列表。
	// 返回的 results_html 为搜索接口返回的原始 HTML 片段，
	// 由调用方负责解析为游戏条目。
	FetchSpecialsPage(ctx context.Context, in *FetchSpecialsPageRequest, opts ...grpc.CallOption) (*SpecialsPage, error)
}

type steamSpecialsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamSpecialsServiceClient(cc grpc.ClientConnInterface) SteamSpecialsServiceClient {
	return &steamSpecialsServiceClient{cc}
}

func (c *steamSpecialsServiceClient) FetchSpecialsPage(ctx context.Context, in *FetchSpecialsPageRequest, opts ...grpc.CallOption) (*SpecialsPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpecialsPage)
	err := c.cc.Invoke(ctx, SteamSpecialsService_FetchSpecialsPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamSpecialsServiceServer is the server API for SteamSpecialsService service.
// All implementations must embed UnimplementedSteamSpecialsServiceServer
// for forward compatibility.
//
// SteamSpecialsService 提供 Steam 折扣游戏列表抓取能力。
// 对应 steam-tasks 中 handlers/steam_specials 的 SteamSpecialsAPI 客户端逻辑。
type SteamSpecialsServiceServer interface {
	// FetchSpecialsPage 获取单页折扣游戏列表。
	// 返回的 results_html 为搜索接口返回的原始 HTML 片段，
	// 由调用方负责解析为游戏条目。
	FetchSpecialsPage(context.Context, *FetchSpecialsPageRequest) (*SpecialsPage, error)
	mustEmbedUnimplementedSteamSpecialsServiceServer()
}

// UnimplementedSteamSpecialsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamSpecialsServiceServer struct{}

func (UnimplementedSteamSpecialsServiceServer) FetchSpecialsPage(context.Context, *FetchSpecialsPageRequest) (*SpecialsPage, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchSpecialsPage not implemented")
}
func (UnimplementedSteamSpecialsServiceServer) mustEmbedUnimplementedSteamSpecialsServiceServer() {}
func (UnimplementedSteamSpecialsServiceServer) testEmbeddedByValue()                              {}

// UnsafeSteamSpecialsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamSpecialsServiceServer will
// result in compilation errors.
type UnsafeSteamSpecialsServiceServer interface {
	mustEmbedUnimplementedSteamSpecialsServiceServer()
}

func RegisterSteamSpecialsServiceServer(s grpc.ServiceRegistrar, srv SteamSpecialsServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamSpecialsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamSpecialsService_ServiceDesc, srv)
}

func _SteamSpecialsService_FetchSpecialsPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchSpecialsPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamSpecialsServiceServer).FetchSpecialsPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamSpecialsService_FetchSpecialsPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamSpecialsServiceServer).FetchSpecialsPage(ctx, req.(*FetchSpecialsPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamSpecialsService_ServiceDesc is the grpc.ServiceDesc for SteamSpecialsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamSpecialsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamspecials.v1.SteamSpecialsService",
	HandlerType: (*SteamSpecialsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSpecialsPage",
			Handler:    _SteamSpecialsService_FetchSpecialsPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamspecials/v1/steamspecials.proto",
}
