// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamspecials/v1/steamspecials.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchSpecialsPageRequest 是 SteamSpecialsService.FetchSpecialsPage 的输入。
type FetchSpecialsPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 起始偏移量（第几个游戏开始），0 为首页。
	Start int32 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// 每页数量。
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSpecialsPageRequest) Reset() {
	*x = FetchSpecialsPageRequest{}
	mi := &file_steamspecials_v1_steamspecials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSpecialsPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSpecialsPageRequest) ProtoMessage() {}

func (x *FetchSpecialsPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamspecials_v1_steamspecials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSpecialsPageRequest.ProtoReflect.Descriptor instead.
func (*FetchSpecialsPageRequest) Descriptor() ([]byte, []int) {
	return file_steamspecials_v1_steamspecials_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSpecialsPageRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FetchSpecialsPageRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SpecialsPage 是一页折扣游戏列表结果。
type SpecialsPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 接口状态码，1 表示成功。
	Success int32 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 搜索结果的原始 HTML 片段。
	ResultsHtml string `protobuf:"bytes,2,opt,name=results_html,json=resultsHtml,proto3" json:"results_html,omitempty"`
	// 折扣游戏总数。
	TotalCount int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// 当前页起始偏移量。
	Start int32 `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	// 每页数量。
	Pagesize      int32 `protobuf:"varint,5,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialsPage) Reset() {
	*x = SpecialsPage{}
	mi := &file_steamspecials_v1_steamspecials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialsPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialsPage) ProtoMessage() {}

func (x *SpecialsPage) ProtoReflect() protoreflect.Message {
	mi := &file_steamspecials_v1_steamspecials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialsPage.ProtoReflect.Descriptor instead.
func (*SpecialsPage) Descriptor() ([]byte, []int) {
	return file_steamspecials_v1_steamspecials_proto_rawDescGZIP(), []int{1}
}

func (x *SpecialsPage) GetSuccess() int32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *SpecialsPage) GetResultsHtml() string {
	if x != nil {
		return x.ResultsHtml
	}
	return ""
}

func (x *SpecialsPage) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SpecialsPage) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SpecialsPage) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

var File_steamspecials_v1_steamspecials_proto protoreflect.FileDescriptor

const file_steamspecials_v1_steamspecials_proto_rawDesc = "" +
	"\n" +
	"$steamspecials/v1/steamspecials.proto\x12\x10steamspecials.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x18FetchSpecialsPageRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x9e\x01\n" +
	"\fSpecialsPage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x05R\asuccess\x12!\n" +
	"\fresults_html\x18\x02 \x01(\tR\vresultsHtml\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x14\n" +
	"\x05start\x18\x04 \x01(\x05R\x05start\x12\x1a\n" +
	"\bpagesize\x18\x05 \x01(\x05R\bpagesize2\x99\x01\n" +
	"\x14SteamSpecialsService\x12\x80\x01\n" +
	"\x11FetchSpecialsPage\x12*.steamspecials.v1.FetchSpecialsPageRequest\x1a\x1e.steamspecials.v1.SpecialsPage\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/steamspecials/pagesBf\n" +
	"\x10steamspecials.v1B\x12SteamSpecialsProtoP\x01Z<github.com/shitamachi/steam-proto-go/api/steamspecials/v1;v1b\x06proto3"

var (
	file_steamspecials_v1_steamspecials_proto_rawDescOnce sync.Once
	file_steamspecials_v1_steamspecials_proto_rawDescData []byte
)

func file_steamspecials_v1_steamspecials_proto_rawDescGZIP() []byte {
	file_steamspecials_v1_steamspecials_proto_rawDescOnce.Do(func() {
		file_steamspecials_v1_steamspecials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamspecials_v1_steamspecials_proto_rawDesc), len(file_steamspecials_v1_steamspecials_proto_rawDesc)))
	})
	return file_steamspecials_v1_steamspecials_proto_rawDescData
}

var file_steamspecials_v1_steamspecials_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steamspecials_v1_steamspecials_proto_goTypes = []any{
	(*FetchSpecialsPageRequest)(nil), // 0: steamspecials.v1.FetchSpecialsPageRequest
	(*SpecialsPage)(nil),             // 1: steamspecials.v1.SpecialsPage
}
var file_steamspecials_v1_steamspecials_proto_depIdxs = []int32{
	0, // 0: steamspecials.v1.SteamSpecialsService.FetchSpecialsPage:input_type -> steamspecials.v1.FetchSpecialsPageRequest
	1, // 1: steamspecials.v1.SteamSpecialsService.FetchSpecialsPage:output_type -> steamspecials.v1.SpecialsPage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steamspecials_v1_steamspecials_proto_init() }
func file_steamspecials_v1_steamspecials_proto_init() {
	if File_steamspecials_v1_steamspecials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamspecials_v1_steamspecials_proto_rawDesc), len(file_steamspecials_v1_steamspecials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamspecials_v1_steamspecials_proto_goTypes,
		DependencyIndexes: file_steamspecials_v1_steamspecials_proto_depIdxs,
		MessageInfos:      file_steamspecials_v1_steamspecials_proto_msgTypes,
	}.Build()
	File_steamspecials_v1_steamspecials_proto = out.File
	file_steamspecials_v1_steamspecials_proto_goTypes = nil
	file_steamspecials_v1_steamspecials_proto_depIdxs = nil
}
