// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: externalfacts/v1/externalfacts.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	steamhttpbinding "github.com/shitamachi/steam-proto-go/internal/httpbinding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationExternalFactsServiceGetExternalFacts = "/externalfacts.v1.ExternalFactsService/GetExternalFacts"

type ExternalFactsServiceHTTPServer interface {
	GetExternalFacts(context.Context, *GetExternalFactsRequest) (*GetExternalFactsResponse, error)
}

func RegisterExternalFactsServiceHTTPServer(s *http.Server, srv ExternalFactsServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/external-facts:collect", _ExternalFactsService_GetExternalFacts0_HTTP_Handler(srv))
}

func _ExternalFactsService_GetExternalFacts0_HTTP_Handler(srv ExternalFactsServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExternalFactsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExternalFactsServiceGetExternalFacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExternalFacts(ctx, req.(*GetExternalFactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExternalFactsResponse)
		return ctx.Result(200, reply)
	}
}

type ExternalFactsServiceHTTPClient interface {
	GetExternalFacts(ctx context.Context, req *GetExternalFactsRequest, opts ...http.CallOption) (rsp *GetExternalFactsResponse, err error)
}

type ExternalFactsServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewExternalFactsServiceHTTPClient(client *http.Client) ExternalFactsServiceHTTPClient {
	return &ExternalFactsServiceHTTPClientImpl{client}
}

func (c *ExternalFactsServiceHTTPClientImpl) GetExternalFacts(ctx context.Context, in *GetExternalFactsRequest, opts ...http.CallOption) (*GetExternalFactsResponse, error) {
	var out GetExternalFactsResponse
	pattern := "/v1/external-facts:collect"
	path := steamhttpbinding.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationExternalFactsServiceGetExternalFacts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
