// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: externalfacts/v1/externalfacts.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fixed-purpose operations; credentials and arbitrary upstream URLs are never accepted.
type GetExternalFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	AppId         int64                  `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	ExternalId    string                 `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Since         string                 `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	ShopId        int64                  `protobuf:"varint,7,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalFactsRequest) Reset() {
	*x = GetExternalFactsRequest{}
	mi := &file_externalfacts_v1_externalfacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalFactsRequest) ProtoMessage() {}

func (x *GetExternalFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalfacts_v1_externalfacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalFactsRequest.ProtoReflect.Descriptor instead.
func (*GetExternalFactsRequest) Descriptor() ([]byte, []int) {
	return file_externalfacts_v1_externalfacts_proto_rawDescGZIP(), []int{0}
}

func (x *GetExternalFactsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetExternalFactsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetExternalFactsRequest) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetExternalFactsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetExternalFactsRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetExternalFactsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *GetExternalFactsRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type GetExternalFactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactsJson     [][]byte               `protobuf:"bytes,1,rep,name=facts_json,json=factsJson,proto3" json:"facts_json,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalFactsResponse) Reset() {
	*x = GetExternalFactsResponse{}
	mi := &file_externalfacts_v1_externalfacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalFactsResponse) ProtoMessage() {}

func (x *GetExternalFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_externalfacts_v1_externalfacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalFactsResponse.ProtoReflect.Descriptor instead.
func (*GetExternalFactsResponse) Descriptor() ([]byte, []int) {
	return file_externalfacts_v1_externalfacts_proto_rawDescGZIP(), []int{1}
}

func (x *GetExternalFactsResponse) GetFactsJson() [][]byte {
	if x != nil {
		return x.FactsJson
	}
	return nil
}

func (x *GetExternalFactsResponse) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

var File_externalfacts_v1_externalfacts_proto protoreflect.FileDescriptor

const file_externalfacts_v1_externalfacts_proto_rawDesc = "" +
	"\n" +
	"$externalfacts/v1/externalfacts.proto\x12\x10externalfacts.v1\x1a\x1cgoogle/api/annotations.proto\"\xca\x01\n" +
	"\x17GetExternalFactsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\x03R\x05appId\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05since\x18\x06 \x01(\tR\x05since\x12\x17\n" +
	"\ashop_id\x18\a \x01(\x03R\x06shopId\"Z\n" +
	"\x18GetExternalFactsResponse\x12\x1d\n" +
	"\n" +
	"facts_json\x18\x01 \x03(\fR\tfactsJson\x12\x1f\n" +
	"\vobserved_at\x18\x02 \x01(\tR\n" +
	"observedAt2\xa9\x01\n" +
	"\x14ExternalFactsService\x12\x90\x01\n" +
	"\x10GetExternalFacts\x12).externalfacts.v1.GetExternalFactsRequest\x1a*.externalfacts.v1.GetExternalFactsResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/external-facts:collectB>Z<github.com/shitamachi/steam-proto-go/api/externalfacts/v1;v1b\x06proto3"

var (
	file_externalfacts_v1_externalfacts_proto_rawDescOnce sync.Once
	file_externalfacts_v1_externalfacts_proto_rawDescData []byte
)

func file_externalfacts_v1_externalfacts_proto_rawDescGZIP() []byte {
	file_externalfacts_v1_externalfacts_proto_rawDescOnce.Do(func() {
		file_externalfacts_v1_externalfacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_externalfacts_v1_externalfacts_proto_rawDesc), len(file_externalfacts_v1_externalfacts_proto_rawDesc)))
	})
	return file_externalfacts_v1_externalfacts_proto_rawDescData
}

var file_externalfacts_v1_externalfacts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_externalfacts_v1_externalfacts_proto_goTypes = []any{
	(*GetExternalFactsRequest)(nil),  // 0: externalfacts.v1.GetExternalFactsRequest
	(*GetExternalFactsResponse)(nil), // 1: externalfacts.v1.GetExternalFactsResponse
}
var file_externalfacts_v1_externalfacts_proto_depIdxs = []int32{
	0, // 0: externalfacts.v1.ExternalFactsService.GetExternalFacts:input_type -> externalfacts.v1.GetExternalFactsRequest
	1, // 1: externalfacts.v1.ExternalFactsService.GetExternalFacts:output_type -> externalfacts.v1.GetExternalFactsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_externalfacts_v1_externalfacts_proto_init() }
func file_externalfacts_v1_externalfacts_proto_init() {
	if File_externalfacts_v1_externalfacts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_externalfacts_v1_externalfacts_proto_rawDesc), len(file_externalfacts_v1_externalfacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_externalfacts_v1_externalfacts_proto_goTypes,
		DependencyIndexes: file_externalfacts_v1_externalfacts_proto_depIdxs,
		MessageInfos:      file_externalfacts_v1_externalfacts_proto_msgTypes,
	}.Build()
	File_externalfacts_v1_externalfacts_proto = out.File
	file_externalfacts_v1_externalfacts_proto_goTypes = nil
	file_externalfacts_v1_externalfacts_proto_depIdxs = nil
}
