// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: externalfacts/v1/externalfacts.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalFactsService_GetExternalFacts_FullMethodName = "/externalfacts.v1.ExternalFactsService/GetExternalFacts"
)

// ExternalFactsServiceClient is the client API for ExternalFactsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalFactsServiceClient interface {
	GetExternalFacts(ctx context.Context, in *GetExternalFactsRequest, opts ...grpc.CallOption) (*GetExternalFactsResponse, error)
}

type externalFactsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalFactsServiceClient(cc grpc.ClientConnInterface) ExternalFactsServiceClient {
	return &externalFactsServiceClient{cc}
}

func (c *externalFactsServiceClient) GetExternalFacts(ctx context.Context, in *GetExternalFactsRequest, opts ...grpc.CallOption) (*GetExternalFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExternalFactsResponse)
	err := c.cc.Invoke(ctx, ExternalFactsService_GetExternalFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalFactsServiceServer is the server API for ExternalFactsService service.
// All implementations must embed UnimplementedExternalFactsServiceServer
// for forward compatibility.
type ExternalFactsServiceServer interface {
	GetExternalFacts(context.Context, *GetExternalFactsRequest) (*GetExternalFactsResponse, error)
	mustEmbedUnimplementedExternalFactsServiceServer()
}

// UnimplementedExternalFactsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalFactsServiceServer struct{}

func (UnimplementedExternalFactsServiceServer) GetExternalFacts(context.Context, *GetExternalFactsRequest) (*GetExternalFactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExternalFacts not implemented")
}
func (UnimplementedExternalFactsServiceServer) mustEmbedUnimplementedExternalFactsServiceServer() {}
func (UnimplementedExternalFactsServiceServer) testEmbeddedByValue()                              {}

// UnsafeExternalFactsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalFactsServiceServer will
// result in compilation errors.
type UnsafeExternalFactsServiceServer interface {
	mustEmbedUnimplementedExternalFactsServiceServer()
}

func RegisterExternalFactsServiceServer(s grpc.ServiceRegistrar, srv ExternalFactsServiceServer) {
	// If the following call panics, it indicates UnimplementedExternalFactsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalFactsService_ServiceDesc, srv)
}

func _ExternalFactsService_GetExternalFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExternalFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalFactsServiceServer).GetExternalFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalFactsService_GetExternalFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalFactsServiceServer).GetExternalFacts(ctx, req.(*GetExternalFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalFactsService_ServiceDesc is the grpc.ServiceDesc for ExternalFactsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalFactsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "externalfacts.v1.ExternalFactsService",
	HandlerType: (*ExternalFactsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExternalFacts",
			Handler:    _ExternalFactsService_GetExternalFacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "externalfacts/v1/externalfacts.proto",
}
