// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamreview/v1/steamreview.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamReviewService_FetchReviewsPage_FullMethodName = "/steamreview.v1.SteamReviewService/FetchReviewsPage"
)

// SteamReviewServiceClient is the client API for SteamReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamReviewService 提供 Steam 评论抓取能力。
// 对应 steam-tasks 中 handlers/steam_review 的 SteamReviewsAPI 客户端逻辑。
type SteamReviewServiceClient interface {
	// FetchReviewsPage 获取单页 Steam 评论原始数据。
	// 返回的 raw_json 为 appreviews 接口的原始 JSON 响应体
	// （包含 reviews / cursor / query_summary 等字段），解析与落库由调用方完成。
	FetchReviewsPage(ctx context.Context, in *FetchReviewsPageRequest, opts ...grpc.CallOption) (*ReviewsPage, error)
}

type steamReviewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamReviewServiceClient(cc grpc.ClientConnInterface) SteamReviewServiceClient {
	return &steamReviewServiceClient{cc}
}

func (c *steamReviewServiceClient) FetchReviewsPage(ctx context.Context, in *FetchReviewsPageRequest, opts ...grpc.CallOption) (*ReviewsPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewsPage)
	err := c.cc.Invoke(ctx, SteamReviewService_FetchReviewsPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamReviewServiceServer is the server API for SteamReviewService service.
// All implementations must embed UnimplementedSteamReviewServiceServer
// for forward compatibility.
//
// SteamReviewService 提供 Steam 评论抓取能力。
// 对应 steam-tasks 中 handlers/steam_review 的 SteamReviewsAPI 客户端逻辑。
type SteamReviewServiceServer interface {
	// FetchReviewsPage 获取单页 Steam 评论原始数据。
	// 返回的 raw_json 为 appreviews 接口的原始 JSON 响应体
	// （包含 reviews / cursor / query_summary 等字段），解析与落库由调用方完成。
	FetchReviewsPage(context.Context, *FetchReviewsPageRequest) (*ReviewsPage, error)
	mustEmbedUnimplementedSteamReviewServiceServer()
}

// UnimplementedSteamReviewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamReviewServiceServer struct{}

func (UnimplementedSteamReviewServiceServer) FetchReviewsPage(context.Context, *FetchReviewsPageRequest) (*ReviewsPage, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchReviewsPage not implemented")
}
func (UnimplementedSteamReviewServiceServer) mustEmbedUnimplementedSteamReviewServiceServer() {}
func (UnimplementedSteamReviewServiceServer) testEmbeddedByValue()                            {}

// UnsafeSteamReviewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamReviewServiceServer will
// result in compilation errors.
type UnsafeSteamReviewServiceServer interface {
	mustEmbedUnimplementedSteamReviewServiceServer()
}

func RegisterSteamReviewServiceServer(s grpc.ServiceRegistrar, srv SteamReviewServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamReviewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamReviewService_ServiceDesc, srv)
}

func _SteamReviewService_FetchReviewsPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchReviewsPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamReviewServiceServer).FetchReviewsPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamReviewService_FetchReviewsPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamReviewServiceServer).FetchReviewsPage(ctx, req.(*FetchReviewsPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamReviewService_ServiceDesc is the grpc.ServiceDesc for SteamReviewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamReviewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamreview.v1.SteamReviewService",
	HandlerType: (*SteamReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchReviewsPage",
			Handler:    _SteamReviewService_FetchReviewsPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamreview/v1/steamreview.proto",
}
