// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamreview/v1/steamreview.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchReviewsPageRequest 是 SteamReviewService.FetchReviewsPage 的输入。
type FetchReviewsPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏的 Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 分页游标，首页传 "*"。
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// 每页评论数量。
	NumPerPage    int32 `protobuf:"varint,3,opt,name=num_per_page,json=numPerPage,proto3" json:"num_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReviewsPageRequest) Reset() {
	*x = FetchReviewsPageRequest{}
	mi := &file_steamreview_v1_steamreview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReviewsPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReviewsPageRequest) ProtoMessage() {}

func (x *FetchReviewsPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamreview_v1_steamreview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReviewsPageRequest.ProtoReflect.Descriptor instead.
func (*FetchReviewsPageRequest) Descriptor() ([]byte, []int) {
	return file_steamreview_v1_steamreview_proto_rawDescGZIP(), []int{0}
}

func (x *FetchReviewsPageRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *FetchReviewsPageRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *FetchReviewsPageRequest) GetNumPerPage() int32 {
	if x != nil {
		return x.NumPerPage
	}
	return 0
}

// ReviewsPage 是一页 Steam 评论抓取结果。
type ReviewsPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏的 Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// appreviews 接口返回的原始 JSON 响应体。
	RawJson       []byte `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewsPage) Reset() {
	*x = ReviewsPage{}
	mi := &file_steamreview_v1_steamreview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewsPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewsPage) ProtoMessage() {}

func (x *ReviewsPage) ProtoReflect() protoreflect.Message {
	mi := &file_steamreview_v1_steamreview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewsPage.ProtoReflect.Descriptor instead.
func (*ReviewsPage) Descriptor() ([]byte, []int) {
	return file_steamreview_v1_steamreview_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewsPage) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ReviewsPage) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

var File_steamreview_v1_steamreview_proto protoreflect.FileDescriptor

const file_steamreview_v1_steamreview_proto_rawDesc = "" +
	"\n" +
	" steamreview/v1/steamreview.proto\x12\x0esteamreview.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"o\n" +
	"\x17FetchReviewsPageRequest\x12\x1a\n" +
	"\x06app_id\x18\x01 \x01(\x05B\x03\xe0A\x02R\x05appId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12 \n" +
	"\fnum_per_page\x18\x03 \x01(\x05R\n" +
	"numPerPage\"?\n" +
	"\vReviewsPage\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\fR\arawJson2\x97\x01\n" +
	"\x12SteamReviewService\x12\x80\x01\n" +
	"\x10FetchReviewsPage\x12'.steamreview.v1.FetchReviewsPageRequest\x1a\x1b.steamreview.v1.ReviewsPage\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/steamreview/pages/{app_id}B`\n" +
	"\x0esteamreview.v1B\x10SteamReviewProtoP\x01Z:github.com/shitamachi/steam-proto-go/api/steamreview/v1;v1b\x06proto3"

var (
	file_steamreview_v1_steamreview_proto_rawDescOnce sync.Once
	file_steamreview_v1_steamreview_proto_rawDescData []byte
)

func file_steamreview_v1_steamreview_proto_rawDescGZIP() []byte {
	file_steamreview_v1_steamreview_proto_rawDescOnce.Do(func() {
		file_steamreview_v1_steamreview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamreview_v1_steamreview_proto_rawDesc), len(file_steamreview_v1_steamreview_proto_rawDesc)))
	})
	return file_steamreview_v1_steamreview_proto_rawDescData
}

var file_steamreview_v1_steamreview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_steamreview_v1_steamreview_proto_goTypes = []any{
	(*FetchReviewsPageRequest)(nil), // 0: steamreview.v1.FetchReviewsPageRequest
	(*ReviewsPage)(nil),             // 1: steamreview.v1.ReviewsPage
}
var file_steamreview_v1_steamreview_proto_depIdxs = []int32{
	0, // 0: steamreview.v1.SteamReviewService.FetchReviewsPage:input_type -> steamreview.v1.FetchReviewsPageRequest
	1, // 1: steamreview.v1.SteamReviewService.FetchReviewsPage:output_type -> steamreview.v1.ReviewsPage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steamreview_v1_steamreview_proto_init() }
func file_steamreview_v1_steamreview_proto_init() {
	if File_steamreview_v1_steamreview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamreview_v1_steamreview_proto_rawDesc), len(file_steamreview_v1_steamreview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamreview_v1_steamreview_proto_goTypes,
		DependencyIndexes: file_steamreview_v1_steamreview_proto_depIdxs,
		MessageInfos:      file_steamreview_v1_steamreview_proto_msgTypes,
	}.Build()
	File_steamreview_v1_steamreview_proto = out.File
	file_steamreview_v1_steamreview_proto_goTypes = nil
	file_steamreview_v1_steamreview_proto_depIdxs = nil
}
