// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: steamreview/v1/steamreview.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamReviewServiceFetchReviewsPage = "/steamreview.v1.SteamReviewService/FetchReviewsPage"

type SteamReviewServiceHTTPServer interface {
	// FetchReviewsPage FetchReviewsPage 获取单页 Steam 评论原始数据。
	// 返回的 raw_json 为 appreviews 接口的原始 JSON 响应体
	// （包含 reviews / cursor / query_summary 等字段），解析与落库由调用方完成。
	FetchReviewsPage(context.Context, *FetchReviewsPageRequest) (*ReviewsPage, error)
}

func RegisterSteamReviewServiceHTTPServer(s *http.Server, srv SteamReviewServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamreview/pages/{app_id}", _SteamReviewService_FetchReviewsPage0_HTTP_Handler(srv))
}

func _SteamReviewService_FetchReviewsPage0_HTTP_Handler(srv SteamReviewServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FetchReviewsPageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamReviewServiceFetchReviewsPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FetchReviewsPage(ctx, req.(*FetchReviewsPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReviewsPage)
		return ctx.Result(200, reply)
	}
}

type SteamReviewServiceHTTPClient interface {
	// FetchReviewsPage FetchReviewsPage 获取单页 Steam 评论原始数据。
	// 返回的 raw_json 为 appreviews 接口的原始 JSON 响应体
	// （包含 reviews / cursor / query_summary 等字段），解析与落库由调用方完成。
	FetchReviewsPage(ctx context.Context, req *FetchReviewsPageRequest, opts ...http.CallOption) (rsp *ReviewsPage, err error)
}

type SteamReviewServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamReviewServiceHTTPClient(client *http.Client) SteamReviewServiceHTTPClient {
	return &SteamReviewServiceHTTPClientImpl{client}
}

// FetchReviewsPage FetchReviewsPage 获取单页 Steam 评论原始数据。
// 返回的 raw_json 为 appreviews 接口的原始 JSON 响应体
// （包含 reviews / cursor / query_summary 等字段），解析与落库由调用方完成。
func (c *SteamReviewServiceHTTPClientImpl) FetchReviewsPage(ctx context.Context, in *FetchReviewsPageRequest, opts ...http.CallOption) (*ReviewsPage, error) {
	var out ReviewsPage
	pattern := "/v1/steamreview/pages/{app_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamReviewServiceFetchReviewsPage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
