// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamdb/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SteamDB 错误原因。
type ErrorReason int32

const (
	// 未指定。
	ErrorReason_STEAMDB_UNSPECIFIED ErrorReason = 0
	// 请求参数不合法。
	ErrorReason_STEAMDB_INVALID_ARGUMENT ErrorReason = 1
	// 上游返回失败状态或数据不合法。
	ErrorReason_STEAMDB_INVALID_DATA ErrorReason = 2
	// 上游网络请求失败。
	ErrorReason_STEAMDB_NETWORK ErrorReason = 3
	// 上游触发 SteamDB 侧限流（429/403），调用方应退避或熔断。
	ErrorReason_STEAMDB_RATE_LIMITED ErrorReason = 4
	// 上游资源已下线（如 SteamDB 下架某榜单页，404/410 或 upstream_removed 标记）。
	// 永久失败：调用方应丢弃任务，不重试、不熔断。
	ErrorReason_STEAMDB_UPSTREAM_GONE ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "STEAMDB_UNSPECIFIED",
		1: "STEAMDB_INVALID_ARGUMENT",
		2: "STEAMDB_INVALID_DATA",
		3: "STEAMDB_NETWORK",
		4: "STEAMDB_RATE_LIMITED",
		5: "STEAMDB_UPSTREAM_GONE",
	}
	ErrorReason_value = map[string]int32{
		"STEAMDB_UNSPECIFIED":      0,
		"STEAMDB_INVALID_ARGUMENT": 1,
		"STEAMDB_INVALID_DATA":     2,
		"STEAMDB_NETWORK":          3,
		"STEAMDB_RATE_LIMITED":     4,
		"STEAMDB_UPSTREAM_GONE":    5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_steamdb_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_steamdb_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_steamdb_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_steamdb_v1_error_reason_proto protoreflect.FileDescriptor

const file_steamdb_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dsteamdb/v1/error_reason.proto\x12\n" +
	"steamdb.v1*\xa8\x01\n" +
	"\vErrorReason\x12\x17\n" +
	"\x13STEAMDB_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STEAMDB_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14STEAMDB_INVALID_DATA\x10\x02\x12\x13\n" +
	"\x0fSTEAMDB_NETWORK\x10\x03\x12\x18\n" +
	"\x14STEAMDB_RATE_LIMITED\x10\x04\x12\x19\n" +
	"\x15STEAMDB_UPSTREAM_GONE\x10\x05B_\n" +
	"\n" +
	"steamdb.v1B\x17SteamDBErrorReasonProtoP\x01Z6github.com/shitamachi/steam-proto-go/api/steamdb/v1;v1b\x06proto3"

var (
	file_steamdb_v1_error_reason_proto_rawDescOnce sync.Once
	file_steamdb_v1_error_reason_proto_rawDescData []byte
)

func file_steamdb_v1_error_reason_proto_rawDescGZIP() []byte {
	file_steamdb_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_steamdb_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamdb_v1_error_reason_proto_rawDesc), len(file_steamdb_v1_error_reason_proto_rawDesc)))
	})
	return file_steamdb_v1_error_reason_proto_rawDescData
}

var file_steamdb_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steamdb_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: steamdb.v1.ErrorReason
}
var file_steamdb_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_steamdb_v1_error_reason_proto_init() }
func file_steamdb_v1_error_reason_proto_init() {
	if File_steamdb_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamdb_v1_error_reason_proto_rawDesc), len(file_steamdb_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_steamdb_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_steamdb_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_steamdb_v1_error_reason_proto_enumTypes,
	}.Build()
	File_steamdb_v1_error_reason_proto = out.File
	file_steamdb_v1_error_reason_proto_goTypes = nil
	file_steamdb_v1_error_reason_proto_depIdxs = nil
}
