// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: steamdb/v1/steamdb.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSteamDBServiceEnrichAppIDs = "/steamdb.v1.SteamDBService/EnrichAppIDs"
const OperationSteamDBServiceGetAppPage = "/steamdb.v1.SteamDBService/GetAppPage"
const OperationSteamDBServiceGetListPage = "/steamdb.v1.SteamDBService/GetListPage"

type SteamDBServiceHTTPServer interface {
	// EnrichAppIDs EnrichAppIDs 富化一组 AppID（SteamDB 扩展 API 玩家统计/历史最低价 +
	// Steam Store 详情 + 在线人数 + 评论摘要 + SteamSpy），不抓取 SteamDB 页面，
	// 是大批量 per-appid 数据的低风险通道。
	// 上游同步串行处理，单个 AppID 约 2~3s，调用方需控制 app_ids 数量（网关超时 120s）。
	EnrichAppIDs(context.Context, *EnrichAppIDsRequest) (*EnrichAppIDsReply, error)
	// GetAppPage GetAppPage 抓取单个 App 的 SteamDB 信息页，可选附带子页（charts/depots/configs）。
	// 返回 raw_json 为上游解析后的 JSON（含 name/developer/价格/tags/DLC/社交链接等）。
	// 注意：history/stats/patchnotes 子页为 JS 渲染，上游不支持。
	GetAppPage(context.Context, *GetAppPageRequest) (*GetAppPageReply, error)
	// GetListPage GetListPage 抓取 SteamDB 列表页（榜单/即将发售/当前折扣），返回 raw_json。
	GetListPage(context.Context, *GetListPageRequest) (*GetListPageReply, error)
}

func RegisterSteamDBServiceHTTPServer(s *http.Server, srv SteamDBServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/steamdb/enrich", _SteamDBService_EnrichAppIDs0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdb/apps/{app_id}", _SteamDBService_GetAppPage0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/steamdb/lists", _SteamDBService_GetListPage0_HTTP_Handler(srv))
}

func _SteamDBService_EnrichAppIDs0_HTTP_Handler(srv SteamDBServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnrichAppIDsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDBServiceEnrichAppIDs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnrichAppIDs(ctx, req.(*EnrichAppIDsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnrichAppIDsReply)
		return ctx.Result(200, reply)
	}
}

func _SteamDBService_GetAppPage0_HTTP_Handler(srv SteamDBServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppPageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDBServiceGetAppPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppPage(ctx, req.(*GetAppPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppPageReply)
		return ctx.Result(200, reply)
	}
}

func _SteamDBService_GetListPage0_HTTP_Handler(srv SteamDBServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetListPageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSteamDBServiceGetListPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetListPage(ctx, req.(*GetListPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetListPageReply)
		return ctx.Result(200, reply)
	}
}

type SteamDBServiceHTTPClient interface {
	// EnrichAppIDs EnrichAppIDs 富化一组 AppID（SteamDB 扩展 API 玩家统计/历史最低价 +
	// Steam Store 详情 + 在线人数 + 评论摘要 + SteamSpy），不抓取 SteamDB 页面，
	// 是大批量 per-appid 数据的低风险通道。
	// 上游同步串行处理，单个 AppID 约 2~3s，调用方需控制 app_ids 数量（网关超时 120s）。
	EnrichAppIDs(ctx context.Context, req *EnrichAppIDsRequest, opts ...http.CallOption) (rsp *EnrichAppIDsReply, err error)
	// GetAppPage GetAppPage 抓取单个 App 的 SteamDB 信息页，可选附带子页（charts/depots/configs）。
	// 返回 raw_json 为上游解析后的 JSON（含 name/developer/价格/tags/DLC/社交链接等）。
	// 注意：history/stats/patchnotes 子页为 JS 渲染，上游不支持。
	GetAppPage(ctx context.Context, req *GetAppPageRequest, opts ...http.CallOption) (rsp *GetAppPageReply, err error)
	// GetListPage GetListPage 抓取 SteamDB 列表页（榜单/即将发售/当前折扣），返回 raw_json。
	GetListPage(ctx context.Context, req *GetListPageRequest, opts ...http.CallOption) (rsp *GetListPageReply, err error)
}

type SteamDBServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSteamDBServiceHTTPClient(client *http.Client) SteamDBServiceHTTPClient {
	return &SteamDBServiceHTTPClientImpl{client}
}

// EnrichAppIDs EnrichAppIDs 富化一组 AppID（SteamDB 扩展 API 玩家统计/历史最低价 +
// Steam Store 详情 + 在线人数 + 评论摘要 + SteamSpy），不抓取 SteamDB 页面，
// 是大批量 per-appid 数据的低风险通道。
// 上游同步串行处理，单个 AppID 约 2~3s，调用方需控制 app_ids 数量（网关超时 120s）。
func (c *SteamDBServiceHTTPClientImpl) EnrichAppIDs(ctx context.Context, in *EnrichAppIDsRequest, opts ...http.CallOption) (*EnrichAppIDsReply, error) {
	var out EnrichAppIDsReply
	pattern := "/v1/steamdb/enrich"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDBServiceEnrichAppIDs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAppPage GetAppPage 抓取单个 App 的 SteamDB 信息页，可选附带子页（charts/depots/configs）。
// 返回 raw_json 为上游解析后的 JSON（含 name/developer/价格/tags/DLC/社交链接等）。
// 注意：history/stats/patchnotes 子页为 JS 渲染，上游不支持。
func (c *SteamDBServiceHTTPClientImpl) GetAppPage(ctx context.Context, in *GetAppPageRequest, opts ...http.CallOption) (*GetAppPageReply, error) {
	var out GetAppPageReply
	pattern := "/v1/steamdb/apps/{app_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDBServiceGetAppPage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetListPage GetListPage 抓取 SteamDB 列表页（榜单/即将发售/当前折扣），返回 raw_json。
func (c *SteamDBServiceHTTPClientImpl) GetListPage(ctx context.Context, in *GetListPageRequest, opts ...http.CallOption) (*GetListPageReply, error) {
	var out GetListPageReply
	pattern := "/v1/steamdb/lists"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSteamDBServiceGetListPage),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
