// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: steamdb/v1/steamdb.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SteamDBService_EnrichAppIDs_FullMethodName = "/steamdb.v1.SteamDBService/EnrichAppIDs"
	SteamDBService_GetAppPage_FullMethodName   = "/steamdb.v1.SteamDBService/GetAppPage"
	SteamDBService_GetListPage_FullMethodName  = "/steamdb.v1.SteamDBService/GetListPage"
)

// SteamDBServiceClient is the client API for SteamDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SteamDBService 提供 SteamDB 数据源代理能力（lg-steamdb-scraper HTTP 服务）。
// 上游为部署在集群内的 steamdb-scraper（默认 https://steamdb.k.mygo.rocks），
// 负责Cloudflare 绕过与多数据源富化；本服务只做透传与轻量封装。
type SteamDBServiceClient interface {
	// EnrichAppIDs 富化一组 AppID（SteamDB 扩展 API 玩家统计/历史最低价 +
	// Steam Store 详情 + 在线人数 + 评论摘要 + SteamSpy），不抓取 SteamDB 页面，
	// 是大批量 per-appid 数据的低风险通道。
	// 上游同步串行处理，单个 AppID 约 2~3s，调用方需控制 app_ids 数量（网关超时 120s）。
	EnrichAppIDs(ctx context.Context, in *EnrichAppIDsRequest, opts ...grpc.CallOption) (*EnrichAppIDsReply, error)
	// GetAppPage 抓取单个 App 的 SteamDB 信息页，可选附带子页（charts/depots/configs）。
	// 返回 raw_json 为上游解析后的 JSON（含 name/developer/价格/tags/DLC/社交链接等）。
	// 注意：history/stats/patchnotes 子页为 JS 渲染，上游不支持。
	GetAppPage(ctx context.Context, in *GetAppPageRequest, opts ...grpc.CallOption) (*GetAppPageReply, error)
	// GetListPage 抓取 SteamDB 列表页（榜单/即将发售/当前折扣），返回 raw_json。
	GetListPage(ctx context.Context, in *GetListPageRequest, opts ...grpc.CallOption) (*GetListPageReply, error)
}

type steamDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSteamDBServiceClient(cc grpc.ClientConnInterface) SteamDBServiceClient {
	return &steamDBServiceClient{cc}
}

func (c *steamDBServiceClient) EnrichAppIDs(ctx context.Context, in *EnrichAppIDsRequest, opts ...grpc.CallOption) (*EnrichAppIDsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichAppIDsReply)
	err := c.cc.Invoke(ctx, SteamDBService_EnrichAppIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steamDBServiceClient) GetAppPage(ctx context.Context, in *GetAppPageRequest, opts ...grpc.CallOption) (*GetAppPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppPageReply)
	err := c.cc.Invoke(ctx, SteamDBService_GetAppPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *steamDBServiceClient) GetListPage(ctx context.Context, in *GetListPageRequest, opts ...grpc.CallOption) (*GetListPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListPageReply)
	err := c.cc.Invoke(ctx, SteamDBService_GetListPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SteamDBServiceServer is the server API for SteamDBService service.
// All implementations must embed UnimplementedSteamDBServiceServer
// for forward compatibility.
//
// SteamDBService 提供 SteamDB 数据源代理能力（lg-steamdb-scraper HTTP 服务）。
// 上游为部署在集群内的 steamdb-scraper（默认 https://steamdb.k.mygo.rocks），
// 负责Cloudflare 绕过与多数据源富化；本服务只做透传与轻量封装。
type SteamDBServiceServer interface {
	// EnrichAppIDs 富化一组 AppID（SteamDB 扩展 API 玩家统计/历史最低价 +
	// Steam Store 详情 + 在线人数 + 评论摘要 + SteamSpy），不抓取 SteamDB 页面，
	// 是大批量 per-appid 数据的低风险通道。
	// 上游同步串行处理，单个 AppID 约 2~3s，调用方需控制 app_ids 数量（网关超时 120s）。
	EnrichAppIDs(context.Context, *EnrichAppIDsRequest) (*EnrichAppIDsReply, error)
	// GetAppPage 抓取单个 App 的 SteamDB 信息页，可选附带子页（charts/depots/configs）。
	// 返回 raw_json 为上游解析后的 JSON（含 name/developer/价格/tags/DLC/社交链接等）。
	// 注意：history/stats/patchnotes 子页为 JS 渲染，上游不支持。
	GetAppPage(context.Context, *GetAppPageRequest) (*GetAppPageReply, error)
	// GetListPage 抓取 SteamDB 列表页（榜单/即将发售/当前折扣），返回 raw_json。
	GetListPage(context.Context, *GetListPageRequest) (*GetListPageReply, error)
	mustEmbedUnimplementedSteamDBServiceServer()
}

// UnimplementedSteamDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSteamDBServiceServer struct{}

func (UnimplementedSteamDBServiceServer) EnrichAppIDs(context.Context, *EnrichAppIDsRequest) (*EnrichAppIDsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichAppIDs not implemented")
}
func (UnimplementedSteamDBServiceServer) GetAppPage(context.Context, *GetAppPageRequest) (*GetAppPageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppPage not implemented")
}
func (UnimplementedSteamDBServiceServer) GetListPage(context.Context, *GetListPageRequest) (*GetListPageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListPage not implemented")
}
func (UnimplementedSteamDBServiceServer) mustEmbedUnimplementedSteamDBServiceServer() {}
func (UnimplementedSteamDBServiceServer) testEmbeddedByValue()                        {}

// UnsafeSteamDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SteamDBServiceServer will
// result in compilation errors.
type UnsafeSteamDBServiceServer interface {
	mustEmbedUnimplementedSteamDBServiceServer()
}

func RegisterSteamDBServiceServer(s grpc.ServiceRegistrar, srv SteamDBServiceServer) {
	// If the following call panics, it indicates UnimplementedSteamDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SteamDBService_ServiceDesc, srv)
}

func _SteamDBService_EnrichAppIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichAppIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamDBServiceServer).EnrichAppIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamDBService_EnrichAppIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamDBServiceServer).EnrichAppIDs(ctx, req.(*EnrichAppIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SteamDBService_GetAppPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamDBServiceServer).GetAppPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamDBService_GetAppPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamDBServiceServer).GetAppPage(ctx, req.(*GetAppPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SteamDBService_GetListPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SteamDBServiceServer).GetListPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SteamDBService_GetListPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SteamDBServiceServer).GetListPage(ctx, req.(*GetListPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SteamDBService_ServiceDesc is the grpc.ServiceDesc for SteamDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SteamDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steamdb.v1.SteamDBService",
	HandlerType: (*SteamDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrichAppIDs",
			Handler:    _SteamDBService_EnrichAppIDs_Handler,
		},
		{
			MethodName: "GetAppPage",
			Handler:    _SteamDBService_GetAppPage_Handler,
		},
		{
			MethodName: "GetListPage",
			Handler:    _SteamDBService_GetListPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steamdb/v1/steamdb.proto",
}
