// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: steamdb/v1/steamdb.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SteamDBListKind 列表页类型。
type SteamDBListKind int32

const (
	// 未指定（默认按榜单处理）。
	SteamDBListKind_STEAM_DB_LIST_KIND_UNSPECIFIED SteamDBListKind = 0
	// 榜单（topsellers/mostwished/mostplayed/topnew/trending）。
	SteamDBListKind_STEAM_DB_LIST_KIND_CHARTS SteamDBListKind = 1
	// 即将发售。
	SteamDBListKind_STEAM_DB_LIST_KIND_UPCOMING SteamDBListKind = 2
	// 当前折扣。
	SteamDBListKind_STEAM_DB_LIST_KIND_SALES SteamDBListKind = 3
)

// Enum value maps for SteamDBListKind.
var (
	SteamDBListKind_name = map[int32]string{
		0: "STEAM_DB_LIST_KIND_UNSPECIFIED",
		1: "STEAM_DB_LIST_KIND_CHARTS",
		2: "STEAM_DB_LIST_KIND_UPCOMING",
		3: "STEAM_DB_LIST_KIND_SALES",
	}
	SteamDBListKind_value = map[string]int32{
		"STEAM_DB_LIST_KIND_UNSPECIFIED": 0,
		"STEAM_DB_LIST_KIND_CHARTS":      1,
		"STEAM_DB_LIST_KIND_UPCOMING":    2,
		"STEAM_DB_LIST_KIND_SALES":       3,
	}
)

func (x SteamDBListKind) Enum() *SteamDBListKind {
	p := new(SteamDBListKind)
	*p = x
	return p
}

func (x SteamDBListKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SteamDBListKind) Descriptor() protoreflect.EnumDescriptor {
	return file_steamdb_v1_steamdb_proto_enumTypes[0].Descriptor()
}

func (SteamDBListKind) Type() protoreflect.EnumType {
	return &file_steamdb_v1_steamdb_proto_enumTypes[0]
}

func (x SteamDBListKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SteamDBListKind.Descriptor instead.
func (SteamDBListKind) EnumDescriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{0}
}

// EnrichAppIDsRequest 是 SteamDBService.EnrichAppIDs 的输入。
type EnrichAppIDsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要富化的 AppID 列表（上游单次上限 50，建议 ≤ 30 以避开网关超时）。
	AppIds []int32 `protobuf:"varint,1,rep,packed,name=app_ids,json=appIds,proto3" json:"app_ids,omitempty"`
	// 逗号分隔的币种列表，如 "CNY,USD"（默认 USD,EUR,GBP；每多一个币种 = 每 AppID 多一次上游调用）。
	Currencies string `protobuf:"bytes,2,opt,name=currencies,proto3" json:"currencies,omitempty"`
	// 是否跳过 Steam 商店详情。
	NoDetails bool `protobuf:"varint,3,opt,name=no_details,json=noDetails,proto3" json:"no_details,omitempty"`
	// 是否跳过历史最低价。
	NoPrices bool `protobuf:"varint,4,opt,name=no_prices,json=noPrices,proto3" json:"no_prices,omitempty"`
	// 是否跳过 SteamSpy 数据。
	NoSteamspy bool `protobuf:"varint,5,opt,name=no_steamspy,json=noSteamspy,proto3" json:"no_steamspy,omitempty"`
	// 相邻 AppID 之间的间隔秒数（0~10，默认 0.3），防止打爆上游。
	DelaySeconds  float64 `protobuf:"fixed64,6,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichAppIDsRequest) Reset() {
	*x = EnrichAppIDsRequest{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichAppIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichAppIDsRequest) ProtoMessage() {}

func (x *EnrichAppIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichAppIDsRequest.ProtoReflect.Descriptor instead.
func (*EnrichAppIDsRequest) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichAppIDsRequest) GetAppIds() []int32 {
	if x != nil {
		return x.AppIds
	}
	return nil
}

func (x *EnrichAppIDsRequest) GetCurrencies() string {
	if x != nil {
		return x.Currencies
	}
	return ""
}

func (x *EnrichAppIDsRequest) GetNoDetails() bool {
	if x != nil {
		return x.NoDetails
	}
	return false
}

func (x *EnrichAppIDsRequest) GetNoPrices() bool {
	if x != nil {
		return x.NoPrices
	}
	return false
}

func (x *EnrichAppIDsRequest) GetNoSteamspy() bool {
	if x != nil {
		return x.NoSteamspy
	}
	return false
}

func (x *EnrichAppIDsRequest) GetDelaySeconds() float64 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

// SteamDBEnrichedApp 是单个 App 的富化结果。
type SteamDBEnrichedApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 上游富化结果的原始 JSON（player_stats / lowest_prices / reviews / steamspy 等），
	// 解析与落库由调用方完成。
	RawJson       []byte `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamDBEnrichedApp) Reset() {
	*x = SteamDBEnrichedApp{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamDBEnrichedApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamDBEnrichedApp) ProtoMessage() {}

func (x *SteamDBEnrichedApp) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamDBEnrichedApp.ProtoReflect.Descriptor instead.
func (*SteamDBEnrichedApp) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{1}
}

func (x *SteamDBEnrichedApp) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SteamDBEnrichedApp) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

// EnrichAppIDsReply 是一次批量富化结果。
type EnrichAppIDsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 上游处理时间（ISO8601）。
	FetchedAt string `protobuf:"bytes,1,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	// 成功富化的 App 列表（失败/不存在的 AppID 会被上游跳过）。
	Apps          []*SteamDBEnrichedApp `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichAppIDsReply) Reset() {
	*x = EnrichAppIDsReply{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichAppIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichAppIDsReply) ProtoMessage() {}

func (x *EnrichAppIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichAppIDsReply.ProtoReflect.Descriptor instead.
func (*EnrichAppIDsReply) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichAppIDsReply) GetFetchedAt() string {
	if x != nil {
		return x.FetchedAt
	}
	return ""
}

func (x *EnrichAppIDsReply) GetApps() []*SteamDBEnrichedApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

// GetAppPageRequest 是 SteamDBService.GetAppPage 的输入。
type GetAppPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 国家代码（价格展示用），默认 ca。
	Cc string `protobuf:"bytes,2,opt,name=cc,proto3" json:"cc,omitempty"`
	// 需要一并抓取的子页列表：charts / depots / configs / all。
	Subpages      []string `protobuf:"bytes,3,rep,name=subpages,proto3" json:"subpages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPageRequest) Reset() {
	*x = GetAppPageRequest{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPageRequest) ProtoMessage() {}

func (x *GetAppPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPageRequest.ProtoReflect.Descriptor instead.
func (*GetAppPageRequest) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppPageRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetAppPageRequest) GetCc() string {
	if x != nil {
		return x.Cc
	}
	return ""
}

func (x *GetAppPageRequest) GetSubpages() []string {
	if x != nil {
		return x.Subpages
	}
	return nil
}

// GetAppPageReply 是 App 信息页抓取结果。
type GetAppPageReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Steam AppID。
	AppId int32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 上游返回的原始 JSON（info 页字段 + 可选 charts/depots/configs 子对象）。
	RawJson       []byte `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPageReply) Reset() {
	*x = GetAppPageReply{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPageReply) ProtoMessage() {}

func (x *GetAppPageReply) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPageReply.ProtoReflect.Descriptor instead.
func (*GetAppPageReply) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppPageReply) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetAppPageReply) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

// GetListPageRequest 是 SteamDBService.GetListPage 的输入。
type GetListPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 列表页类型。
	Kind SteamDBListKind `protobuf:"varint,1,opt,name=kind,proto3,enum=steamdb.v1.SteamDBListKind" json:"kind,omitempty"`
	// kind=CHARTS 时必填：topsellers / mostwished / mostplayed / topnew / trending。
	ChartType string `protobuf:"bytes,2,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
	// 国家代码（价格展示用），默认 ca。
	Cc string `protobuf:"bytes,3,opt,name=cc,proto3" json:"cc,omitempty"`
	// kind=UPCOMING 时可选：周标识，如 2025W26；为空则取当前周。
	Week string `protobuf:"bytes,4,opt,name=week,proto3" json:"week,omitempty"`
	// kind=UPCOMING 时可选：类型过滤（Game/DLC/...），默认 Game。
	DisplayOnly string `protobuf:"bytes,5,opt,name=display_only,json=displayOnly,proto3" json:"display_only,omitempty"`
	// kind=SALES 时可选：最低折扣百分比（0~100）。
	MinDiscount   int32 `protobuf:"varint,6,opt,name=min_discount,json=minDiscount,proto3" json:"min_discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPageRequest) Reset() {
	*x = GetListPageRequest{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPageRequest) ProtoMessage() {}

func (x *GetListPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPageRequest.ProtoReflect.Descriptor instead.
func (*GetListPageRequest) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{5}
}

func (x *GetListPageRequest) GetKind() SteamDBListKind {
	if x != nil {
		return x.Kind
	}
	return SteamDBListKind_STEAM_DB_LIST_KIND_UNSPECIFIED
}

func (x *GetListPageRequest) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

func (x *GetListPageRequest) GetCc() string {
	if x != nil {
		return x.Cc
	}
	return ""
}

func (x *GetListPageRequest) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

func (x *GetListPageRequest) GetDisplayOnly() string {
	if x != nil {
		return x.DisplayOnly
	}
	return ""
}

func (x *GetListPageRequest) GetMinDiscount() int32 {
	if x != nil {
		return x.MinDiscount
	}
	return 0
}

// GetListPageReply 是列表页抓取结果。
type GetListPageReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 列表页类型（回显）。
	Kind SteamDBListKind `protobuf:"varint,1,opt,name=kind,proto3,enum=steamdb.v1.SteamDBListKind" json:"kind,omitempty"`
	// 请求参数回显（JSON，如 {"chart_type":"topsellers"}）。
	ParamsJson []byte `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	// 上游返回的原始 JSON（榜单 items / upcoming games / sales 列表）。
	RawJson       []byte `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListPageReply) Reset() {
	*x = GetListPageReply{}
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListPageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPageReply) ProtoMessage() {}

func (x *GetListPageReply) ProtoReflect() protoreflect.Message {
	mi := &file_steamdb_v1_steamdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPageReply.ProtoReflect.Descriptor instead.
func (*GetListPageReply) Descriptor() ([]byte, []int) {
	return file_steamdb_v1_steamdb_proto_rawDescGZIP(), []int{6}
}

func (x *GetListPageReply) GetKind() SteamDBListKind {
	if x != nil {
		return x.Kind
	}
	return SteamDBListKind_STEAM_DB_LIST_KIND_UNSPECIFIED
}

func (x *GetListPageReply) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *GetListPageReply) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

var File_steamdb_v1_steamdb_proto protoreflect.FileDescriptor

const file_steamdb_v1_steamdb_proto_rawDesc = "" +
	"\n" +
	"\x18steamdb/v1/steamdb.proto\x12\n" +
	"steamdb.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xd5\x01\n" +
	"\x13EnrichAppIDsRequest\x12\x1c\n" +
	"\aapp_ids\x18\x01 \x03(\x05B\x03\xe0A\x02R\x06appIds\x12\x1e\n" +
	"\n" +
	"currencies\x18\x02 \x01(\tR\n" +
	"currencies\x12\x1d\n" +
	"\n" +
	"no_details\x18\x03 \x01(\bR\tnoDetails\x12\x1b\n" +
	"\tno_prices\x18\x04 \x01(\bR\bnoPrices\x12\x1f\n" +
	"\vno_steamspy\x18\x05 \x01(\bR\n" +
	"noSteamspy\x12#\n" +
	"\rdelay_seconds\x18\x06 \x01(\x01R\fdelaySeconds\"F\n" +
	"\x12SteamDBEnrichedApp\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\fR\arawJson\"f\n" +
	"\x11EnrichAppIDsReply\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\x01 \x01(\tR\tfetchedAt\x122\n" +
	"\x04apps\x18\x02 \x03(\v2\x1e.steamdb.v1.SteamDBEnrichedAppR\x04apps\"[\n" +
	"\x11GetAppPageRequest\x12\x1a\n" +
	"\x06app_id\x18\x01 \x01(\x05B\x03\xe0A\x02R\x05appId\x12\x0e\n" +
	"\x02cc\x18\x02 \x01(\tR\x02cc\x12\x1a\n" +
	"\bsubpages\x18\x03 \x03(\tR\bsubpages\"C\n" +
	"\x0fGetAppPageReply\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\fR\arawJson\"\xd3\x01\n" +
	"\x12GetListPageRequest\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.steamdb.v1.SteamDBListKindB\x03\xe0A\x02R\x04kind\x12\x1d\n" +
	"\n" +
	"chart_type\x18\x02 \x01(\tR\tchartType\x12\x0e\n" +
	"\x02cc\x18\x03 \x01(\tR\x02cc\x12\x12\n" +
	"\x04week\x18\x04 \x01(\tR\x04week\x12!\n" +
	"\fdisplay_only\x18\x05 \x01(\tR\vdisplayOnly\x12!\n" +
	"\fmin_discount\x18\x06 \x01(\x05R\vminDiscount\"\x7f\n" +
	"\x10GetListPageReply\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.steamdb.v1.SteamDBListKindR\x04kind\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\fR\n" +
	"paramsJson\x12\x19\n" +
	"\braw_json\x18\x03 \x01(\fR\arawJson*\x93\x01\n" +
	"\x0fSteamDBListKind\x12\"\n" +
	"\x1eSTEAM_DB_LIST_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19STEAM_DB_LIST_KIND_CHARTS\x10\x01\x12\x1f\n" +
	"\x1bSTEAM_DB_LIST_KIND_UPCOMING\x10\x02\x12\x1c\n" +
	"\x18STEAM_DB_LIST_KIND_SALES\x10\x032\xd1\x02\n" +
	"\x0eSteamDBService\x12j\n" +
	"\fEnrichAppIDs\x12\x1f.steamdb.v1.EnrichAppIDsRequest\x1a\x1d.steamdb.v1.EnrichAppIDsReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/steamdb/enrich\x12k\n" +
	"\n" +
	"GetAppPage\x12\x1d.steamdb.v1.GetAppPageRequest\x1a\x1b.steamdb.v1.GetAppPageReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/steamdb/apps/{app_id}\x12f\n" +
	"\vGetListPage\x12\x1e.steamdb.v1.GetListPageRequest\x1a\x1c.steamdb.v1.GetListPageReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/steamdb/listsBT\n" +
	"\n" +
	"steamdb.v1B\fSteamDBProtoP\x01Z6github.com/shitamachi/steam-proto-go/api/steamdb/v1;v1b\x06proto3"

var (
	file_steamdb_v1_steamdb_proto_rawDescOnce sync.Once
	file_steamdb_v1_steamdb_proto_rawDescData []byte
)

func file_steamdb_v1_steamdb_proto_rawDescGZIP() []byte {
	file_steamdb_v1_steamdb_proto_rawDescOnce.Do(func() {
		file_steamdb_v1_steamdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_steamdb_v1_steamdb_proto_rawDesc), len(file_steamdb_v1_steamdb_proto_rawDesc)))
	})
	return file_steamdb_v1_steamdb_proto_rawDescData
}

var file_steamdb_v1_steamdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_steamdb_v1_steamdb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_steamdb_v1_steamdb_proto_goTypes = []any{
	(SteamDBListKind)(0),        // 0: steamdb.v1.SteamDBListKind
	(*EnrichAppIDsRequest)(nil), // 1: steamdb.v1.EnrichAppIDsRequest
	(*SteamDBEnrichedApp)(nil),  // 2: steamdb.v1.SteamDBEnrichedApp
	(*EnrichAppIDsReply)(nil),   // 3: steamdb.v1.EnrichAppIDsReply
	(*GetAppPageRequest)(nil),   // 4: steamdb.v1.GetAppPageRequest
	(*GetAppPageReply)(nil),     // 5: steamdb.v1.GetAppPageReply
	(*GetListPageRequest)(nil),  // 6: steamdb.v1.GetListPageRequest
	(*GetListPageReply)(nil),    // 7: steamdb.v1.GetListPageReply
}
var file_steamdb_v1_steamdb_proto_depIdxs = []int32{
	2, // 0: steamdb.v1.EnrichAppIDsReply.apps:type_name -> steamdb.v1.SteamDBEnrichedApp
	0, // 1: steamdb.v1.GetListPageRequest.kind:type_name -> steamdb.v1.SteamDBListKind
	0, // 2: steamdb.v1.GetListPageReply.kind:type_name -> steamdb.v1.SteamDBListKind
	1, // 3: steamdb.v1.SteamDBService.EnrichAppIDs:input_type -> steamdb.v1.EnrichAppIDsRequest
	4, // 4: steamdb.v1.SteamDBService.GetAppPage:input_type -> steamdb.v1.GetAppPageRequest
	6, // 5: steamdb.v1.SteamDBService.GetListPage:input_type -> steamdb.v1.GetListPageRequest
	3, // 6: steamdb.v1.SteamDBService.EnrichAppIDs:output_type -> steamdb.v1.EnrichAppIDsReply
	5, // 7: steamdb.v1.SteamDBService.GetAppPage:output_type -> steamdb.v1.GetAppPageReply
	7, // 8: steamdb.v1.SteamDBService.GetListPage:output_type -> steamdb.v1.GetListPageReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_steamdb_v1_steamdb_proto_init() }
func file_steamdb_v1_steamdb_proto_init() {
	if File_steamdb_v1_steamdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_steamdb_v1_steamdb_proto_rawDesc), len(file_steamdb_v1_steamdb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_steamdb_v1_steamdb_proto_goTypes,
		DependencyIndexes: file_steamdb_v1_steamdb_proto_depIdxs,
		EnumInfos:         file_steamdb_v1_steamdb_proto_enumTypes,
		MessageInfos:      file_steamdb_v1_steamdb_proto_msgTypes,
	}.Build()
	File_steamdb_v1_steamdb_proto = out.File
	file_steamdb_v1_steamdb_proto_goTypes = nil
	file_steamdb_v1_steamdb_proto_depIdxs = nil
}
